#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


#python manage.py migrate
if [ $DEBUGPY_ON == 0 ]; then
    exec python manage.py runserver_plus 0.0.0.0:8000
else
    python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
fi
