# Generated by Django 2.0.3 on 2018-07-18 20:27

import django.core.validators
from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuschange',
            name='date',
        ),
        migrations.AlterField(
            model_name='initiation',
            name='test_a',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='initiation',
            name='test_b',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='date_end',
            field=models.DateTimeField(blank=True, default=forms.models.forever),
        ),
    ]
