# Generated by Django 2.2.12 on 2020-05-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_auto_20200517_1020"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiationprocess",
            name="initiations",
            field=models.ManyToManyField(
                blank=True, related_name="process", to="forms.Initiation"
            ),
        ),
        migrations.AlterField(
            model_name="pledgeprocess",
            name="pledges",
            field=models.ManyToManyField(
                blank=True, related_name="process", to="forms.Pledge"
            ),
        ),
    ]
