# Generated by Django 2.0.3 on 2018-08-18 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0002_auto_20180718_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2018)),
                ('term', models.CharField(choices=[('fa', 'Fall'), ('sp', 'Spring'), ('wi', 'Winter'), ('su', 'Summer')], max_length=2)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('alcohol', models.BooleanField()),
                ('hosting', models.BooleanField()),
                ('monitoring', models.BooleanField()),
                ('member', models.BooleanField()),
                ('officer', models.BooleanField()),
                ('abusive', models.BooleanField()),
                ('hazing', models.BooleanField()),
                ('substances', models.BooleanField()),
                ('high_risk', models.BooleanField()),
                ('transportation', models.BooleanField()),
                ('property_management', models.BooleanField()),
                ('guns', models.BooleanField()),
                ('trademark', models.BooleanField()),
                ('social', models.BooleanField()),
                ('indemnification', models.BooleanField()),
                ('agreement', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_form', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
