# Generated by Django 2.0.3 on 2018-09-03 16:55

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_initial_badge_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depledge',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='initiation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='initiation',
            name='date_graduation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='date_end',
            field=models.DateField(blank=True, default=core.models.forever),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statuschange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
