# Generated by Django 2.2.12 on 2020-07-05 06:57

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0004_gender_nonbinary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depledge",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[core.models.no_future],
                verbose_name="Depledge Date",
            ),
        ),
        migrations.AlterField(
            model_name="initiation",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[core.models.no_future],
                verbose_name="Initiation Date",
            ),
        ),
    ]
