# Generated by Django 2.0.3 on 2018-09-04 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20180903_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='new_school',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='chapters.Chapter'),
        ),
    ]
