# Generated by Django 2.2.12 on 2020-07-19 05:12

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_disciplinary_process"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinaryprocess",
            name="final_letter",
            field=models.FileField(
                default="Test", upload_to=forms.models.get_discipline_upload_path
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="disciplinaryprocess",
            name="outcome_letter",
            field=models.FileField(
                default="Test", upload_to=forms.models.get_discipline_upload_path
            ),
            preserve_default=False,
        ),
    ]
