# Generated by Django 2.2.12 on 2020-08-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0006_disciplinary_process"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statuschange",
            name="reason",
            field=models.CharField(
                choices=[
                    ("graduate", "Member is graduating"),
                    ("coop", "Member is going on CoOp or Study abroad"),
                    ("covid", "Member is leaving for the semester due to COVID-19"),
                    ("military", "Member is being deployed"),
                    ("withdraw", "Member is withdrawing from school"),
                    ("transfer", "Member is transferring to another school"),
                ],
                max_length=10,
            ),
        ),
    ]
