# Generated by Django 2.2.12 on 2020-07-20 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0007_auto_20200718_2212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplinaryprocess",
            name="suspension_end",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="If suspended, when will this member’s suspension end?",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryprocess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discipline",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Name of Accused",
            ),
        ),
    ]
