# Generated by Django 2.2.12 on 2020-07-20 02:25

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0008_auto_20200719_1835"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplinaryprocess",
            name="punishment",
            field=models.CharField(
                choices=[("expelled", "Expelled"), ("suspended", "Suspended")],
                default="suspended",
                max_length=100,
                verbose_name="What was the punishment agreed to by the chapter?",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryprocess",
            name="punishment_other",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="What other punishments, if any, were agreed to by the chapter?",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryprocess",
            name="results_letter",
            field=models.FileField(
                blank=True,
                help_text="Please attach a copy of the letter you sent to the member informing them of the outcome of the trial.",
                null=True,
                upload_to=forms.models.get_discipline_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryprocess",
            name="why_take",
            field=models.CharField(
                blank=True,
                choices=[
                    ("waived", "Accused Waived Right to Trial"),
                    ("rescheduled", "Rescheduled"),
                ],
                max_length=100,
                null=True,
                verbose_name="Why did the trial not take place?",
            ),
        ),
    ]
