# Generated by Django 2.2.12 on 2020-08-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0009_resignationprocess"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiationprocess",
            name="ceremony",
            field=models.CharField(
                choices=[
                    ("normal", "Normal in-person ceremony"),
                    ("extra", "In-person extraordinary initiation ceremony"),
                    ("remote", "Remote extraordinary initiation ceremony"),
                ],
                default="normal",
                max_length=10,
                verbose_name="What ceremony did you use to initiate these members?",
            ),
        ),
    ]
