# Generated by Django 2.0.3 on 2018-10-21 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_auto_20180908_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='new_school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='chapters.Chapter'),
        ),
    ]
