# Generated by Django 2.2.12 on 2020-08-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0010_initiationprocess_ceremony"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskmanagement",
            name="fines",
            field=models.BooleanField(default=False),
        ),
    ]
