# Generated by Django 2.0.3 on 2018-12-09 21:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0010_initial_curricula'),
        ('forms', '0010_auto_20181021_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name of Pledge')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_forms', to='chapters.Chapter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
