# Generated by Django 2.2.12 on 2020-07-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0010_auto_20200719_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplinaryprocess",
            name="ec_approval",
            field=models.BooleanField(
                choices=[
                    (True, "Outcome approved by EC"),
                    (False, "Outcome Rejected by EC"),
                ],
                default=False,
                verbose_name="Executive Council Outcome",
            ),
        ),
    ]
