# Generated by Django 2.0.3 on 2018-12-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_pledgeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledgeform',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Pledge Name'),
        ),
        migrations.AlterUniqueTogether(
            name='pledgeform',
            unique_together={('name', 'email')},
        ),
    ]
