# Generated by Django 2.2.12 on 2020-07-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0011_auto_20200719_2236"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinaryprocess",
            name="advisor_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="If yes, alumni advisor name",
            ),
        ),
        migrations.AddField(
            model_name="disciplinaryprocess",
            name="faculty_name",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="If yes, campus/faculty adviser name",
            ),
        ),
    ]
