# Generated by Django 2.2.12 on 2020-10-03 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("forms", "0012_auto_20200903_2152"),
    ]

    operations = [
        migrations.RemoveField(model_name="pledge", name="address",),
        migrations.RemoveField(model_name="pledge", name="birth_date",),
        migrations.RemoveField(model_name="pledge", name="email_personal",),
        migrations.RemoveField(model_name="pledge", name="email_school",),
        migrations.RemoveField(model_name="pledge", name="first_name",),
        migrations.RemoveField(model_name="pledge", name="grad_date_year",),
        migrations.RemoveField(model_name="pledge", name="last_name",),
        migrations.RemoveField(model_name="pledge", name="major",),
        migrations.RemoveField(model_name="pledge", name="middle_name",),
        migrations.RemoveField(model_name="pledge", name="nickname",),
        migrations.RemoveField(model_name="pledge", name="phone_home",),
        migrations.RemoveField(model_name="pledge", name="phone_mobile",),
        migrations.RemoveField(model_name="pledge", name="school_name",),
        migrations.RemoveField(model_name="pledge", name="suffix",),
        migrations.RemoveField(model_name="pledge", name="title",),
        migrations.AddField(
            model_name="pledge",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pledge_form",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(name="PledgeForm",),
    ]
