# Generated by Django 2.2.12 on 2020-10-12 00:06

from django.db import migrations, models
import django.db.models.deletion


def set_init_chapter(apps, schema_editor):
    initiation = apps.get_model("forms", "Initiation")
    for init in initiation.objects.all():
        init.chapter = init.user.chapter
        init.save()


def empty(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0005_chaptercurricula_approved"),
        ("forms", "0013_auto_20201003_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiation",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiations",
                to="chapters.Chapter",
            ),
        ),
        migrations.RunPython(set_init_chapter, empty),
    ]
