# Generated by Django 2.0.3 on 2019-01-13 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0013_auto_20181210_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2019)),
                ('term', models.CharField(choices=[('fa', 'Fall'), ('sp', 'Spring'), ('wi', 'Winter'), ('su', 'Summer')], max_length=2)),
                ('dues_member', models.FloatField(verbose_name='Member Dues')),
                ('dues_pledge', models.FloatField(verbose_name='Potential New Member Pledging Fees/Dues')),
                ('frequency', models.CharField(choices=[('month', 'month'), ('semester', 'semester'), ('quarter', 'quarter'), ('year', 'year')], max_length=10)),
                ('payment_plan', models.BooleanField()),
                ('cash_book', models.BooleanField()),
                ('cash_register', models.BooleanField()),
                ('member_account', models.BooleanField()),
                ('cash_book_reviewed', models.BooleanField()),
                ('cash_register_reviewed', models.BooleanField()),
                ('member_account_reviewed', models.BooleanField()),
                ('balance_checking', models.FloatField()),
                ('balance_savings', models.FloatField()),
                ('debit_card', models.BooleanField()),
                ('debit_card_access', multiselectfield.db.fields.MultiSelectField(choices=[('adviser', 'Adviser'), ('board member', 'Board Member'), ('committee chair', 'Committee Chair'), ('corresponding secretary', 'Corresponding Secretary'), ('employer/ee', 'Employer/Ee'), ('events chair', 'Events Chair'), ('faculty adviser', 'Faculty Adviser'), ('fundraising chair', 'Fundraising Chair'), ('house corporation president', 'House Corporation President'), ('house corporation treasurer', 'House Corporation Treasurer'), ('housing chair', 'Housing Chair'), ('national director', 'National Director'), ('national officer', 'National Officer'), ('other appointee', 'Other Appointee'), ('parent', 'Parent'), ('pd chair', 'Pd Chair'), ('pledge/new member educator', 'Pledge/New Member Educator'), ('president', 'President'), ('project chair', 'Project Chair'), ('recruitment chair', 'Recruitment Chair'), ('regent', 'Regent'), ('regional director', 'Regional Director'), ('risk management chair', 'Risk Management Chair'), ('rube goldberg chair', 'Rube Goldberg Chair'), ('scholarship chair', 'Scholarship Chair'), ('scribe', 'Scribe'), ('secretary', 'Secretary'), ('service chair', 'Service Chair'), ('social/brotherhood chair', 'Social/Brotherhood Chair'), ('treasurer', 'Treasurer'), ('vice president', 'Vice President'), ('vice regent', 'Vice Regent'), ('website/social media chair', 'Website/Social Media Chair')], max_length=530)),
                ('agreement', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_form', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='pledgeprogram',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2019),
        ),
        migrations.AlterField(
            model_name='riskmanagement',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2019),
        ),
    ]
