# Generated by Django 2.2.12 on 2020-10-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0014_initiation_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="resignationprocess",
            name="approved_exec",
            field=models.BooleanField(
                default=False, verbose_name="Executive Director Approved"
            ),
        ),
        migrations.AddField(
            model_name="resignationprocess",
            name="exec_comments",
            field=models.TextField(
                blank=True, verbose_name="If rejecting, please explain why."
            ),
        ),
    ]
