# Generated by Django 2.0.3 on 2019-01-14 00:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0014_auto_20190113_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='balance_checking',
            field=models.FloatField(verbose_name='Balance of chapter checking account'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='balance_savings',
            field=models.FloatField(verbose_name='Balance of chapter savings account'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='debit_card_access',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('None', 'None'), ('adviser', 'Adviser'), ('board member', 'Board Member'), ('committee chair', 'Committee Chair'), ('corresponding secretary', 'Corresponding Secretary'), ('employer/ee', 'Employer/Ee'), ('events chair', 'Events Chair'), ('faculty adviser', 'Faculty Adviser'), ('fundraising chair', 'Fundraising Chair'), ('house corporation president', 'House Corporation President'), ('house corporation treasurer', 'House Corporation Treasurer'), ('housing chair', 'Housing Chair'), ('national director', 'National Director'), ('national officer', 'National Officer'), ('other appointee', 'Other Appointee'), ('parent', 'Parent'), ('pd chair', 'Pd Chair'), ('pledge/new member educator', 'Pledge/New Member Educator'), ('president', 'President'), ('project chair', 'Project Chair'), ('recruitment chair', 'Recruitment Chair'), ('regent', 'Regent'), ('regional director', 'Regional Director'), ('risk management chair', 'Risk Management Chair'), ('rube goldberg chair', 'Rube Goldberg Chair'), ('scholarship chair', 'Scholarship Chair'), ('scribe', 'Scribe'), ('secretary', 'Secretary'), ('service chair', 'Service Chair'), ('social/brotherhood chair', 'Social/Brotherhood Chair'), ('treasurer', 'Treasurer'), ('vice president', 'Vice President'), ('vice regent', 'Vice Regent'), ('website/social media chair', 'Website/Social Media Chair')], max_length=535, verbose_name='Which members have access to the chapter debit card? Select all that apply.'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='frequency',
            field=models.CharField(choices=[('month', 'month'), ('semester', 'semester'), ('quarter', 'quarter'), ('year', 'year')], max_length=10, verbose_name='What is the frequency of member dues'),
        ),
    ]
