# Generated by Django 2.2.12 on 2020-12-30 21:58

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_auto_20160213_1726"),
        ("forms", "0016_returnstudent"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplinaryprocess",
            name="address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.Address",
                verbose_name="Mailing Address of Accused",
            ),
        ),
    ]
