# Generated by Django 2.2.3 on 2019-08-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_auto_20190217_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmanagement',
            name='electronic_agreement',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='terms_agreement',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='typed_name',
            field=models.CharField(default='User Name', max_length=255),
            preserve_default=False,
        ),
    ]
