# Generated by Django 2.2.3 on 2019-08-03 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0006_auto_20180909_1337'),
        ('forms', '0017_auto_20190803_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmanagement',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_management_forms', to='submissions.Submission'),
        ),
    ]
