# Generated by Django 2.2.12 on 2021-01-19 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0018_year_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiationprocess",
            name="scheduled_date",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Date order scheduled to be shipped on",
            ),
        ),
    ]
