# Generated by Django 2.2.12 on 2021-04-28 03:08

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0019_initiationprocess_scheduled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="initiationprocess",
            name="badge_order",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=forms.models.get_badge_order_upload_path,
            ),
        ),
    ]
