# Generated by Django 2.2.3 on 2019-11-11 03:53

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0021_auto_20191110_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='grad_date',
        ),
        migrations.AddField(
            model_name='pledge',
            name='grad_date_year',
            field=models.IntegerField(default=2019, help_text='The year closest to your expected date of graduation in YYYY format.', validators=[core.models.validate_year], verbose_name='Expected date of graduation'),
            preserve_default=False,
        ),
    ]
