# Generated by Django 2.2.12 on 2021-08-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0021_auto_20210726_1000"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplinaryprocess",
            name="ec_approval",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Outcome approved by EC"),
                    (False, "Outcome Rejected by EC"),
                    ("", "Not reviewed yet"),
                ],
                default="",
                null=True,
                verbose_name="Executive Council Outcome",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryprocess",
            name="ed_process",
            field=models.CharField(
                blank=True,
                choices=[
                    ("process", "Accept and Process"),
                    ("accept", "Accept With No Action"),
                    ("reject", "Reject"),
                    ("not_review", "Not Reviewed"),
                ],
                default="not_review",
                max_length=10,
                null=True,
                verbose_name="Executive Director Review",
            ),
        ),
    ]
