# Generated by Django 2.2.12 on 2021-12-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0022_default_disc_opts"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledge",
            name="bill",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                verbose_name="I understand and have read the potential new member bill of rights.",
            ),
        ),
    ]
