# Generated by Django 2.2.3 on 2019-11-11 05:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0022_auto_20191110_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='phone_home',
            field=models.CharField(help_text='Format: 9999999999 no spaces, dashes, etc.', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Home Phone'),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='phone_mobile',
            field=models.CharField(help_text='Format: 9999999999 no spaces, dashes, etc.', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Mobile Phone'),
        ),
    ]
