# Generated by Django 2.2.12 on 2022-01-06 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0023_pledgeprogram_process"),
        ("forms", "0023_auto_20220101_1355"),
        ("forms", "0023_pledge_bill"),
    ]

    operations = []
