# Generated by Django 2.2.12 on 2022-01-17 01:10

import core.models
from django.db import migrations, models
import django.utils.timezone
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0024_merge_20220106_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="depledge",
            name="concerns",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Did the depledged PNM express any concerns?",
            ),
        ),
        migrations.AddField(
            model_name="depledge",
            name="extra_notes",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Is there anything else national Theta Tau should know?",
            ),
        ),
        migrations.AddField(
            model_name="depledge",
            name="informed",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="By whom and how was the depledged PNM informed?",
            ),
        ),
        migrations.AddField(
            model_name="depledge",
            name="meeting_attend",
            field=forms.models.MultiSelectField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("adviser", "Adviser"),
                    ("board member", "Board Member"),
                    ("committee chair", "Committee Chair"),
                    ("corresponding secretary", "Corresponding Secretary"),
                    ("employer/ee", "Employer/Ee"),
                    ("events chair", "Events Chair"),
                    ("faculty adviser", "Faculty Adviser"),
                    ("fundraising chair", "Fundraising Chair"),
                    ("house corporation president", "House Corporation President"),
                    ("house corporation treasurer", "House Corporation Treasurer"),
                    ("housing chair", "Housing Chair"),
                    ("marshal", "Marshal"),
                    ("other appointee", "Other Appointee"),
                    ("parent", "Parent"),
                    ("pd chair", "Pd Chair"),
                    ("pledge/new member educator", "Pledge/New Member Educator"),
                    ("project chair", "Project Chair"),
                    ("recruitment chair", "Recruitment Chair"),
                    ("regent", "Regent"),
                    ("risk management chair", "Risk Management Chair"),
                    ("rube goldberg chair", "Rube Goldberg Chair"),
                    ("scholarship chair", "Scholarship Chair"),
                    ("scribe", "Scribe"),
                    ("service chair", "Service Chair"),
                    ("social/brotherhood chair", "Social/Brotherhood Chair"),
                    ("treasurer", "Treasurer"),
                    ("vice regent", "Vice Regent"),
                    ("website/social media chair", "Website/Social Media Chair"),
                ],
                max_length=455,
                null=True,
                verbose_name="Who attended the meeting with the depledged PNM?",
            ),
        ),
        migrations.AddField(
            model_name="depledge",
            name="meeting_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                validators=[core.models.no_future],
                verbose_name="When was the meeting with the depledged PNM?",
            ),
        ),
        migrations.AddField(
            model_name="depledge",
            name="meeting_held",
            field=models.CharField(
                choices=[
                    ("virtual", "Virtual"),
                    ("in_person", "In Person"),
                    ("no", "No"),
                    ("na", "Not Applicable"),
                ],
                default="na",
                max_length=10,
                verbose_name="Was a meeting held with the depledged PNM?",
            ),
        ),
        migrations.AddField(
            model_name="depledge",
            name="meeting_not",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Why was there no Meeting with the depledged PNM?",
            ),
        ),
        migrations.AddField(
            model_name="depledge",
            name="reason_other",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Other reason for depledging",
            ),
        ),
        migrations.AddField(
            model_name="depledge",
            name="returned_items",
            field=forms.models.MultiSelectField(
                blank=True,
                choices=[
                    ("pin", "Pledge Pin"),
                    ("manual", "Membership Manual"),
                    ("other", "Other"),
                ],
                max_length=10,
                null=True,
                verbose_name="Have the following items been returned?",
            ),
        ),
        migrations.AddField(
            model_name="depledge",
            name="returned_other",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Other returned items",
            ),
        ),
    ]
