# Generated by Django 2.2.3 on 2019-12-30 18:27

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0024_chapterreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterreport',
            name='report',
            field=models.FileField(default=None, upload_to=forms.models.get_chapter_report_upload_path),
            preserve_default=False,
        ),
    ]
