# Generated by Django 2.2.3 on 2019-12-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0025_auto_20191230_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskmanagement',
            name='arbitration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='dues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riskmanagement',
            name='photo_release',
            field=models.BooleanField(default=False),
        ),
    ]
