# Generated by Django 2.2.12 on 2022-02-05 16:38

from django.db import migrations
import forms.models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0025_auto_20220116_1810"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depledge",
            name="returned_items",
            field=forms.models.MultiSelectField(
                blank=True,
                choices=[
                    ("pin", "Pledge Pin"),
                    ("manual", "Membership Manual"),
                    ("other", "Other"),
                    ("na", "No Items Given"),
                ],
                max_length=10,
                null=True,
                verbose_name="Have the following items been returned?",
            ),
        ),
    ]
