# Generated by Django 2.2.12 on 2022-02-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0026_auto_20220205_0938"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prematurealumnus",
            name="semesters",
            field=models.BooleanField(
                default=False,
                verbose_name="Member has completed at least six months of active membership.",
            ),
        ),
    ]
