# Generated by Django 2.2.3 on 2020-02-23 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0027_auto_20200103_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrematureAlumnus',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('form', models.FileField(upload_to=forms.models.get_premature_alumn_upload_path)),
                ('good_standing', models.BooleanField(default=False, verbose_name='Member is in good standing of Theta Tau.')),
                ('financial', models.BooleanField(default=False, verbose_name='Member has no current financial obligation to the chapter.')),
                ('fee', models.BooleanField(default=False, verbose_name='I have remitted $80 Processing Fee with this form request.')),
                ('semesters', models.BooleanField(default=False, verbose_name='Member has completed at least 2 semesters of active membership.')),
                ('lifestyle', models.BooleanField(default=False, verbose_name='Member has had a significant lifestyle change preventing adequately & responsibly fulfilling duties & obligations.')),
                ('consideration', models.BooleanField(default=False, verbose_name='I understand that this status change request is submitted to the Executive Director for consideration.')),
                ('prealumn_type', models.CharField(choices=[('less4', 'Undergraduate Student (initiated into Theta Tau less than four years ago.)'), ('more4', 'Undergraduate Student initiated into Theta Tau 4 or more years ago.'), ('grad', 'Student in Graduate school at the school where initiated as an undergraduate.')], default='less4', max_length=10, verbose_name='Type of Premature (“Early”) Alumnus Status')),
                ('approved_exec', models.BooleanField(default=False, verbose_name='Executive Director Approved')),
                ('exec_comments', models.TextField(blank=True, verbose_name='If rejecting, please explain why.')),
                ('vote', models.BooleanField(default=False, verbose_name='The status change for the member was approved by a four-fifths favorable vote of the chapter.')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prealumn_form', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
