# Generated by Django 2.2.3 on 2020-02-19 06:48

from django.db import migrations, models
import django.db.models.deletion
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
        ('forms', '0027_auto_20200103_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrematureAlumnus',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('form', models.FileField(upload_to=forms.models.get_premature_alumn_upload_path)),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
