# Generated by Django 2.2.3 on 2020-03-15 23:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0027_auto_20200103_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgeprogram',
            name='date_complete',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='When do you anticipate completing new member education?'),
        ),
        migrations.AddField(
            model_name='pledgeprogram',
            name='date_initiation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='When do you plan to hold initiations?'),
        ),
        migrations.AddField(
            model_name='pledgeprogram',
            name='remote',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Will your new member education be run remotely?'),
        ),
    ]
