# Generated by Django 2.2.3 on 2020-02-28 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0028_prematurealumnus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prematurealumnus',
            name='fee',
        ),
    ]
