# Generated by Django 2.2.3 on 2020-02-21 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0028_prematurealumnus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prematurealumnus',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='prematurealumnus',
            name='form',
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='approved_exec',
            field=models.BooleanField(default=False, verbose_name='Executive Director Approved'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='fee',
            field=models.BooleanField(default=False, verbose_name='I have remitted $80 Processing Fee with this form request.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='financial',
            field=models.BooleanField(default=False, verbose_name='I have no current financial obligation to the chapter.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='good_standing',
            field=models.BooleanField(default=False, verbose_name='I am a member in good standing of Theta Tau.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='lifestyle',
            field=models.BooleanField(default=False, verbose_name='I have had a significant lifestyle change preventing me from adequately & responsibly fulfilling my duties & obligations.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='officer1_ack',
            field=models.BooleanField(default=False, verbose_name='I attest that I have received the Premature Alumnus Request from the member.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='officer2_ack',
            field=models.BooleanField(default=False, verbose_name='I attest that I have received the Premature Alumnus Request from the member.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='officers',
            field=models.ManyToManyField(related_name='approve_prealumn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='prealumn_type',
            field=models.CharField(choices=[('less4', 'Undergraduate Student (initiated into Theta Tau less than four years ago.)'), ('more4', 'Undergraduate Student initiated into Theta Tau 4 or more years ago.'), ('grad', 'Student in Graduate school at the school where initiated as an undergraduate.')], default='less4', max_length=10, verbose_name='Type of Premature (“Early”) Alumnus Status'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='semesters',
            field=models.BooleanField(default=False, verbose_name='I have completed at least 2 semesters of active membership.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='signature',
            field=models.CharField(default='', help_text='Please sign using your proper/legal name', max_length=255),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='understand',
            field=models.BooleanField(default=False, verbose_name='If this change is affected, I understand that I will become a full alumnus member of Theta Tau and can only return to Student Member status by separate petition.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='verbose_consideration',
            field=models.BooleanField(default=False, verbose_name='I understand that this status change request is submitted to the Executive Director for consideration.'),
        ),
    ]
