# Generated by Django 2.2.12 on 2022-07-03 03:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0011_chapter_extra_approval"),
        ("forms", "0029_chaptereducation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bylaws",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "bylaws",
                    models.FileField(
                        upload_to=forms.models.get_chapter_bylaws_upload_path
                    ),
                ),
                ("changes", models.TextField(verbose_name="Summary of Changes")),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bylaws",
                        to="chapters.Chapter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
