# Generated by Django 2.2.3 on 2020-03-02 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0016_auto_20200103_1544'),
        ('viewflow', '0008_jsonfield_and_artifact'),
        ('forms', '0029_remove_prematurealumnus_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiationProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiation_process', to='chapters.Chapter')),
                ('initiations', models.ManyToManyField(blank=True, null=True, related_name='process', to='forms.Initiation')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
