# Generated by Django 2.2.3 on 2020-02-23 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0030_auto_20200221_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='prematurealumnus',
            name='exec_comments',
            field=models.TextField(blank=True, verbose_name='If rejecting, please explain why.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='form',
            field=models.FileField(blank=True, null=True, upload_to=forms.models.get_premature_alumn_upload_path),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='officer1_comments',
            field=models.TextField(blank=True, verbose_name='If rejecting, please explain why.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='officer1_vote',
            field=models.BooleanField(default=False, verbose_name='The status change for the member was approved by a four-fifths favorable vote of the chapter.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='officer2_comments',
            field=models.TextField(blank=True, verbose_name='If rejecting, please explain why.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='officer2_vote',
            field=models.BooleanField(default=False, verbose_name='The status change for the member was approved by a four-fifths favorable vote of the chapter.'),
        ),
        migrations.AddField(
            model_name='prematurealumnus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prealumn_form', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prematurealumnus',
            name='officer1_ack',
            field=models.BooleanField(default=False, verbose_name='I verify the information entered on the premature alumnus form is correct.'),
        ),
        migrations.AlterField(
            model_name='prematurealumnus',
            name='officer2_ack',
            field=models.BooleanField(default=False, verbose_name='I verify the information entered on the premature alumnus form is correct.'),
        ),
    ]
