# Generated by Django 3.2.15 on 2022-08-21 01:12

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0030_bylaws"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="debit_card_access",
            field=forms.models.MultiSelectField(
                choices=[
                    ("None", "None"),
                    ("adviser", "Adviser"),
                    ("board member", "Board Member"),
                    ("committee chair", "Committee Chair"),
                    ("corresponding secretary", "Corresponding Secretary"),
                    ("employer/ee", "Employer/Ee"),
                    ("events chair", "Events Chair"),
                    ("faculty adviser", "Faculty Adviser"),
                    ("fundraising chair", "Fundraising Chair"),
                    ("house corporation president", "House Corporation President"),
                    ("house corporation treasurer", "House Corporation Treasurer"),
                    ("housing chair", "Housing Chair"),
                    ("marshal", "Marshal"),
                    ("other appointee", "Other Appointee"),
                    ("parent", "Parent"),
                    ("pd chair", "Pd Chair"),
                    ("pledge/new member educator", "Pledge/New Member Educator"),
                    ("project chair", "Project Chair"),
                    ("recruitment chair", "Recruitment Chair"),
                    ("regent", "Regent"),
                    ("risk management chair", "Risk Management Chair"),
                    ("rube goldberg chair", "Rube Goldberg Chair"),
                    ("scholarship chair", "Scholarship Chair"),
                    ("scribe", "Scribe"),
                    ("service chair", "Service Chair"),
                    ("social/brotherhood chair", "Social/Brotherhood Chair"),
                    ("treasurer", "Treasurer"),
                    ("vice regent", "Vice Regent"),
                    ("website/social media chair", "Website/Social Media Chair"),
                ],
                max_length=5000,
                verbose_name="Which members have access to the chapter debit card? Select all that apply.",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="bylaws",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="chapterreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="collectionreferral",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="depledge",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="depledge",
            name="meeting_attend",
            field=forms.models.MultiSelectField(
                blank=True,
                choices=[
                    ("None", "None"),
                    ("pledge/new member educator", "Pledge/New Member Educator"),
                    ("recruitment chair", "Recruitment Chair"),
                    ("risk management chair", "Risk Management Chair"),
                    ("marshal", "Marshal"),
                    ("other appointee", "Other Appointee"),
                    ("corresponding secretary", "Corresponding Secretary"),
                    ("regent", "Regent"),
                    ("scribe", "Scribe"),
                    ("treasurer", "Treasurer"),
                    ("vice regent", "Vice Regent"),
                ],
                max_length=500,
                null=True,
                verbose_name="Who attended the meeting with the depledged PNM?",
            ),
        ),
        migrations.AlterField(
            model_name="depledge",
            name="returned_items",
            field=forms.models.MultiSelectField(
                blank=True,
                choices=[
                    ("pin", "Pledge Pin"),
                    ("manual", "Membership Manual"),
                    ("other", "Other"),
                    ("na", "No Items Given"),
                ],
                max_length=100,
                null=True,
                verbose_name="Have the following items been returned?",
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryattachment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryprocess",
            name="notify_method",
            field=forms.models.MultiSelectField(
                choices=[
                    ("postal", "Postal Mail"),
                    ("email", "Email"),
                    ("text", "Text Message"),
                    ("social", "Social Media"),
                    ("phone", "Phone Call"),
                    ("person", "In Person"),
                    ("chat", "Chat Message"),
                ],
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="guard",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="initiation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pledgeprogram",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="riskmanagement",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="statuschange",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
