# Generated by Django 3.2.15 on 2022-09-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0031_auto_20220820_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskmanagement",
            name="role",
            field=models.CharField(max_length=254),
        ),
    ]
