# Generated by Django 2.2.3 on 2020-03-09 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0016_auto_20200103_1544'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewflow', '0008_jsonfield_and_artifact'),
        ('forms', '0031_initiationprocess_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('year', models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027)], default=2020)),
                ('term', models.CharField(choices=[('fa', 'Fall'), ('sp', 'Spring'), ('wi', 'Winter'), ('su', 'Summer')], max_length=2)),
                ('meeting_date', models.DateField(default=django.utils.timezone.now)),
                ('signature_del', models.CharField(help_text='Please sign using your proper/legal name', max_length=255)),
                ('signature_alt', models.CharField(help_text='Please sign using your proper/legal name', max_length=255)),
                ('signature_o1', models.CharField(help_text='Please sign using your proper/legal name', max_length=255)),
                ('signature_o2', models.CharField(help_text='Please sign using your proper/legal name', max_length=255)),
                ('approved_o1', models.BooleanField(default=False, verbose_name='Officer Approved')),
                ('approved_o2', models.BooleanField(default=False, verbose_name='Officer Approved')),
                ('alternate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate', to=settings.AUTH_USER_MODEL)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convention', to='chapters.Chapter')),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate', to=settings.AUTH_USER_MODEL)),
                ('officer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_off1', to=settings.AUTH_USER_MODEL)),
                ('officer2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_off2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process', models.Model),
        ),
    ]
