# Generated by Django 2.2.3 on 2020-03-09 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0032_convention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='alternate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate', to=settings.AUTH_USER_MODEL, verbose_name='Alternate Signature'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegate', to=settings.AUTH_USER_MODEL, verbose_name='Delegate Signature'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='officer1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_off1', to=settings.AUTH_USER_MODEL, verbose_name='Officer Signature'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='officer2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conv_off2', to=settings.AUTH_USER_MODEL, verbose_name='Officer Signature'),
        ),
    ]
