# Generated by Django 3.2.15 on 2022-12-17 16:45

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0032_alter_riskmanagement_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledgeprogram",
            name="test",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=forms.models.get_pledge_program_upload_path,
            ),
        ),
    ]
