# Generated by Django 2.2.3 on 2020-03-24 04:09
from django.db import migrations
from django.contrib.auth.models import Group, Permission


PERMISSIONS = [
    'can_start_prematurealumnus',
]


def set_permissions(apps, schema_editor):
    nat_group, created = Group.objects.get_or_create(name='natoff')
    off_group, created = Group.objects.get_or_create(name='officer')
    for perm in PERMISSIONS:
        permission = Permission.objects.get(codename=perm)
        nat_group.permissions.add(permission)
        off_group.permissions.add(permission)


def delete(apps, schema_editor):
    nat_group, created = Group.objects.get_or_create(name='natoff')
    off_group, created = Group.objects.get_or_create(name='officer')
    for perm in PERMISSIONS:
        permission = Permission.objects.get(codename=perm)
        nat_group.permissions.remove(permission)
        off_group.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0033_auto_20200308_2136'),
    ]

    operations = [
        migrations.RunPython(set_permissions, delete),
    ]
