# Generated by Django 2.2.12 on 2020-04-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0034_group_perm_conv_prealumn_init'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='approved_o1',
            field=models.BooleanField(choices=[(True, 'Approve'), (False, 'Deny')], default=False, verbose_name='Officer Approved'),
        ),
        migrations.AlterField(
            model_name='convention',
            name='approved_o2',
            field=models.BooleanField(choices=[(True, 'Approve'), (False, 'Deny')], default=False, verbose_name='Officer Approved'),
        ),
    ]
