# Generated by Django 2.2.12 on 2020-04-09 03:01

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0035_auto_20200408_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='meeting_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[core.models.no_future]),
        ),
    ]
