# Generated by Django 3.2.15 on 2023-10-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0035_alter_audit_debit_card_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resignationprocess",
            name="fee",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                verbose_name="I have or will submit the Resignation Processing Fee to the chapter.",
            ),
        ),
        migrations.AlterField(
            model_name="resignationprocess",
            name="fee_paid",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                verbose_name="Member submitted the Resignation Processing Fee to the chapter.",
            ),
        ),
    ]
