# Generated by Django 2.2.12 on 2020-04-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0036_auto_20200408_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='understand_alt',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I have read and understand the "Convention Expenses" and the "Alcohol Policy\n        for National Meetings" policies in the Theta Tau Policies and Procedures Manual.'),
        ),
        migrations.AddField(
            model_name='convention',
            name='understand_del',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='I have read and understand the "Convention Expenses" and the "Alcohol Policy\n        for National Meetings" policies in the Theta Tau Policies and Procedures Manual.'),
        ),
    ]
