# Generated by Django 2.2.12 on 2020-04-26 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
        ('chapters', '0016_auto_20200103_1544'),
        ('forms', '0037_auto_20200410_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='PledgeProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.Process')),
                ('invoice', models.PositiveIntegerField(default=999999999, verbose_name='Invoice Number')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledge_process', to='chapters.Chapter')),
                ('pledges', models.ManyToManyField(blank=True, null=True, related_name='process', to='forms.Pledge')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
