# Generated by Django 3.2.15 on 2024-03-17 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import email_signals.models
import forms.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chapters", "0013_chapter_nme_file_id"),
        ("forms", "0037_auto_20231231_2219"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniExclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "date_vote",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date of Vote"
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Start Date"
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        help_text="Must be less than 4 months", verbose_name="End Date"
                    ),
                ),
                (
                    "voting_result",
                    models.FloatField(verbose_name="Percentage Voting in Favor"),
                ),
                ("reason", models.TextField(verbose_name="Reason for Exclusion")),
                (
                    "minutes",
                    models.FileField(
                        upload_to=forms.models.get_chapter_exclusions_upload_path
                    ),
                ),
                (
                    "regional_director_veto",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "veto_reason",
                    models.TextField(verbose_name="Reason for RD Exclusion Veto"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_alumni",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluded Alumni",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(models.Model, email_signals.models.EmailSignalMixin),
        ),
    ]
