# Generated by Django 2.2.12 on 2020-04-30 04:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0038_pledgeprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledgeprogram',
            name='status',
            field=models.CharField(choices=[('none', ''), ('initiated', 'We completed new member education and initiated our pledges.'), ('still_initiate', 'We completed new member education and voted, we just have to initiate our pledges.'), ('still_vote', 'We completed new member education but we still need to vote and initiate our pledges.'), ('not_complete', 'We did not complete new member education.')], default='none', max_length=20, verbose_name='What is the current status of your new member education?'),
        ),
        migrations.AddField(
            model_name='pledgeprogram',
            name='weeks',
            field=models.PositiveIntegerField(default=0, verbose_name='How many weeks is your typical new member education program?'),
        ),
        migrations.AddField(
            model_name='pledgeprogram',
            name='weeks_left',
            field=models.PositiveIntegerField(default=0, verbose_name='How many weeks of new member education do you have yet to complete?'),
        ),
        migrations.AlterField(
            model_name='pledgeprogram',
            name='date_complete',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='When did you/do you anticipate completing new member education?'),
        ),
        migrations.AlterField(
            model_name='pledgeprogram',
            name='date_initiation',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='When did you/do you plan to initiate your pledges?'),
        ),
        migrations.AlterField(
            model_name='pledgeprogram',
            name='remote',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Have you or will you conduct your new member education remotely?'),
        ),
    ]
