# Generated by Django 3.2.15 on 2024-08-22 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0038_auto_20240819_2143"),
    ]

    operations = [
        migrations.AddField(
            model_name="pledge",
            name="parent_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Parent / Guardian Email",
            ),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="parent_name",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Parent / Guardian Name",
            ),
        ),
    ]
