# Generated by Django 3.2.15 on 2024-08-25 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import email_signals.models
import forms.models


class Migration(migrations.Migration):
    dependencies = [
        ("chapters", "0013_chapter_nme_file_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("viewflow", "0008_jsonfield_and_artifact"),
        ("forms", "0039_auto_20240821_2149"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniExclusion",
            fields=[
                (
                    "process_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.process",
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "meeting_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date of Vote"
                    ),
                ),
                (
                    "date_start",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Start Date"
                    ),
                ),
                (
                    "date_end",
                    models.DateField(
                        help_text="Must be less than 4 months", verbose_name="End Date"
                    ),
                ),
                (
                    "voting_result",
                    models.FloatField(verbose_name="Percentage Voting in Favor"),
                ),
                ("reason", models.TextField(verbose_name="Reason for Exclusion")),
                (
                    "minutes",
                    models.FileField(
                        upload_to=forms.models.get_chapter_exclusions_upload_path
                    ),
                ),
                (
                    "regional_director_veto",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "Veto")],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "veto_reason",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Reason for RD Exclusion Veto",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exclusions",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "regional_director",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_exclusion",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Officer Signature",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="excluded_alumni",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Excluded Alumni",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                "viewflow.process",
                models.Model,
                email_signals.models.EmailSignalMixin,
            ),
        ),
    ]
