# Generated by Django 4.2.23 on 2026-07-05, then edited to preserve any
# free-form text values that landed in `statuschange.new_school_other`
# between 0042 (added as CharField) and this migration.

import re

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def _clean(name):
    """Whitespace-normalize but preserve casing for display."""
    s = (name or "").strip()
    s = re.sub(r"\s+", " ", s)
    return s.rstrip(" .,;:")


def _key(name):
    """Case-folded dedup key: collapses whitespace and trailing punctuation."""
    s = _clean(name).casefold()
    return re.sub(r"\s+", " ", s).strip(" .,;:")


def populate_new_school_other_fk(apps, schema_editor):
    OtherSchool = apps.get_model("forms", "OtherSchool")
    Chapter = apps.get_model("chapters", "Chapter")
    StatusChange = apps.get_model("forms", "StatusChange")

    # Skip anything that duplicates an existing Chapter.school — those should
    # have been picked from the New School dropdown (and will be during future
    # edits); we do not create an OtherSchool row for them.
    chapter_keys = {_key(s) for s in Chapter.objects.values_list("school", flat=True) if s}

    key_to_school = {}
    qs = StatusChange.objects.exclude(new_school_other_old="").exclude(new_school_other_old__isnull=True)
    for sc in qs.iterator():
        cleaned = _clean(sc.new_school_other_old)
        key = _key(cleaned)
        if not key or key in chapter_keys:
            continue
        school = key_to_school.get(key)
        if school is None:
            school = OtherSchool.objects.filter(name__iexact=cleaned).first()
            if school is None:
                # Another row in this batch may already hold the exact-cased
                # name (unique=True), so fall back to get_or_create.
                school, _ = OtherSchool.objects.get_or_create(name=cleaned)
            key_to_school[key] = school
        sc.new_school_other = school
        sc.save(update_fields=["new_school_other"])


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0042_statuschange_new_school_other"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtherSchool",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Other School (no Theta Tau chapter)",
                "verbose_name_plural": "Other Schools (no Theta Tau chapter)",
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="statuschange",
            old_name="new_school_other",
            new_name="new_school_other_old",
        ),
        migrations.AddField(
            model_name="statuschange",
            name="new_school_other",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transfers",
                to="forms.otherschool",
                verbose_name="Other School (no Theta Tau chapter)",
            ),
        ),
        migrations.RunPython(populate_new_school_other_fk, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="statuschange",
            name="new_school_other_old",
        ),
    ]
