# Generated by Django 4.2.23 on 2026-07-05, then edited to preserve
# existing text values from the old CharField `statuschange.employer`.

import re

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


# Trailing legal / entity suffixes that should not by themselves make two
# employer names look distinct (e.g. "Boeing" vs "Boeing, Inc.").
_SUFFIX_RE = re.compile(
    r",?\s*(inc|incorporated|llc|l\.l\.c\.|corp|corporation|co|company|"
    r"ltd|limited|plc|llp|lp|gmbh)\.?$",
    re.IGNORECASE,
)


def _clean(name):
    """Whitespace-normalize but preserve casing for display."""
    s = (name or "").strip()
    s = re.sub(r"\s+", " ", s)
    return s.rstrip(" .,;:")


def _key(name):
    """Case-folded dedup key: collapses whitespace, strips punctuation and
    common company suffixes."""
    s = _clean(name).casefold()
    s = _SUFFIX_RE.sub("", s)
    s = re.sub(r"\s+", " ", s).strip(" .,;:")
    return s


def populate_employer_fk(apps, schema_editor):
    Employer = apps.get_model("forms", "Employer")
    StatusChange = apps.get_model("forms", "StatusChange")
    key_to_employer = {}
    qs = StatusChange.objects.exclude(employer_old="").exclude(employer_old__isnull=True)
    for sc in qs.iterator():
        cleaned = _clean(sc.employer_old)
        key = _key(cleaned)
        if not key:
            continue
        emp = key_to_employer.get(key)
        if emp is None:
            # Prefer an existing case-insensitive match, else create with the
            # cleaned original casing (which is a better display than an
            # arbitrary lowercase key).
            emp = Employer.objects.filter(name__iexact=cleaned).first()
            if emp is None:
                # Absolute-last-resort: another StatusChange row in this batch
                # may have already reserved the exact-name spot (unique=True).
                emp, _ = Employer.objects.get_or_create(name=cleaned)
            key_to_employer[key] = emp
        sc.employer = emp
        sc.save(update_fields=["employer"])


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0043_otherschool"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Employer",
                "verbose_name_plural": "Employers",
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="statuschange",
            old_name="employer",
            new_name="employer_old",
        ),
        migrations.AddField(
            model_name="statuschange",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="status_changes",
                to="forms.employer",
            ),
        ),
        migrations.RunPython(populate_employer_fk, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="statuschange",
            name="employer_old",
        ),
    ]
