# Generated by Django 4.2.23 on 2026-07-10 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chapters", "0015_add_address_socials_to_chapter"),
        ("events", "0009_alter_event_chapter"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("attended", "Attended")], default="attended", max_length=20)),
                (
                    "was_active",
                    models.BooleanField(
                        default=False, help_text="Member's active status at the time attendance was recorded."
                    ),
                ),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "chapter",
                    models.ForeignKey(
                        help_text="Snapshot of the member's home chapter at record time (differs from the event chapter for guests).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_records",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="events.event",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
                "unique_together": {("event", "user")},
            },
        ),
    ]
