# Generated by Django 4.2.23 on 2026-07-10 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def migrate_existing_to_attended(apps, schema_editor):
    """WI-4: existing attendance rows predate the lifecycle states → 'attended'."""
    AttendanceRecord = apps.get_model("attendance", "AttendanceRecord")
    AttendanceRecord.objects.exclude(status__in=["signed_up", "attended", "no_show"]).update(status="attended")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="previous_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="transitioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[("signed_up", "Signed Up"), ("attended", "Attended"), ("no_show", "No Show")],
                default="attended",
                max_length=20,
            ),
        ),
        migrations.RunPython(migrate_existing_to_attended, noop_reverse),
        migrations.CreateModel(
            name="AttendanceStatusTransition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("from_status", models.CharField(blank=True, default="", max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transitions",
                        to="attendance.attendancerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at", "pk"],
            },
        ),
    ]
