# Generated by Django 4.2.23 on 2026-07-10 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_alter_event_chapter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("attendance", "0002_attendancerecord_previous_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchQueueItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "upload_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, help_text="Groups all rows that arrived in the same upload."
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Stable hash of the raw identity fields; keeps re-uploads idempotent.",
                        max_length=64,
                    ),
                ),
                ("raw_member_id", models.CharField(blank=True, default="", max_length=100)),
                ("raw_badge_number", models.CharField(blank=True, default="", max_length=100)),
                ("raw_email", models.CharField(blank=True, default="", max_length=255)),
                ("raw_name", models.CharField(blank=True, default="", max_length=255)),
                ("raw_first_name", models.CharField(blank=True, default="", max_length=255)),
                ("raw_last_name", models.CharField(blank=True, default="", max_length=255)),
                ("raw_chapter", models.CharField(blank=True, default="", max_length=255)),
                ("raw_graduation_year", models.CharField(blank=True, default="", max_length=16)),
                (
                    "raw_row",
                    models.JSONField(
                        blank=True, default=dict, help_text="The full original upload row, preserved for audit."
                    ),
                ),
                ("candidates", models.JSONField(blank=True, default=list)),
                (
                    "best_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence (0..1) of the top candidate (below the auto-accept threshold).",
                    ),
                ),
                (
                    "target_status",
                    models.CharField(
                        choices=[("signed_up", "Signed Up"), ("attended", "Attended"), ("no_show", "No Show")],
                        default="attended",
                        help_text="Attendance status to assign when this row is resolved.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending Review"), ("resolved", "Resolved"), ("skipped", "Skipped")],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "attendance_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_queue_items",
                        to="attendance.attendancerecord",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="match_queue_items", to="events.event"
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_matches_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_match_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [models.Index(fields=["event", "status"], name="attendance__event_i_416423_idx")],
            },
        ),
    ]
