# Generated by Django 2.2.3 on 2019-10-05 19:51

import ballots.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sender', models.CharField(default='Grand Scribe', max_length=50, verbose_name='From')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('colony', 'Colony Petition'), ('chapter', 'Chapter Petition'), ('suspension', 'Suspension'), ('other', 'Other')], max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=ballots.models.get_ballot_attachment_upload_path)),
                ('description', models.TextField()),
                ('due_date', models.DateField(default=ballots.models.return_date_time)),
                ('voters', models.CharField(choices=[('convention', 'Theta Tau Convention'), ('council', 'Theta Tau Executive Council'), ('nat_off', 'Theta Tau National Officers')], default='convention', max_length=50)),
            ],
            options={
                'unique_together': {('name', 'due_date')},
            },
        ),
        migrations.CreateModel(
            name='BallotComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('motion', models.CharField(choices=[('aye', 'Aye'), ('nay', 'Nay'), ('abstain', 'Abstain')], max_length=20)),
                ('role', models.CharField(choices=[('corresponding secretary', 'Corresponding Secretary'), ('national director', 'National Director'), ('national officer', 'National Officer'), ('regent', 'Regent'), ('regional director', 'Regional Director'), ('scribe', 'Scribe'), ('treasurer', 'Treasurer'), ('vice regent', 'Vice Regent')], max_length=50)),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed', to='ballots.Ballot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'ballot')},
            },
        ),
    ]
