# Generated by Django 2.2.3 on 2019-10-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballotcomplete',
            name='role',
            field=models.CharField(choices=[('alumni programs director', 'Alumni Programs Director'), ('colony director', 'Colony Director'), ('corresponding secretary', 'Corresponding Secretary'), ('council delegate', 'Council Delegate'), ('expansion director', 'Expansion Director'), ('grand inner guard', 'Grand Inner Guard'), ('grand marshal', 'Grand Marshal'), ('grand outer guard', 'Grand Outer Guard'), ('grand regent', 'Grand Regent'), ('grand scribe', 'Grand Scribe'), ('grand treasurer', 'Grand Treasurer'), ('grand vice regent', 'Grand Vice Regent'), ('national director', 'National Director'), ('national officer', 'National Officer'), ('national operations manager', 'National Operations Manager'), ('professional development director', 'Professional Development Director'), ('regent', 'Regent'), ('regional director', 'Regional Director'), ('scribe', 'Scribe'), ('service director', 'Service Director'), ('treasurer', 'Treasurer'), ('vice regent', 'Vice Regent')], max_length=50),
        ),
    ]
