# Generated by Django 2.2.12 on 2020-05-17 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ballots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballotcomplete",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ballots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ballot",
            unique_together={("name", "due_date")},
        ),
        migrations.AlterUniqueTogether(
            name="ballotcomplete",
            unique_together={("user", "ballot")},
        ),
    ]
