# Generated by Django 3.2.15 on 2022-10-23 02:56

import ballots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballots", "0002_auto_20220820_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="voters",
            field=ballots.models.MultiSelectField(
                choices=[
                    ("all_chapters", "All Chapters"),
                    ("alumni programs director", "Alumni Programs Director"),
                    ("candidate chapter director", "Candidate Chapter Director"),
                    ("council delegate", "Council Delegate"),
                    (
                        "educational foundation board of director",
                        "Educational Foundation Board Of Director",
                    ),
                    ("expansion director", "Expansion Director"),
                    ("grand inner guard", "Grand Inner Guard"),
                    ("grand marshal", "Grand Marshal"),
                    ("grand outer guard", "Grand Outer Guard"),
                    ("grand regent", "Grand Regent"),
                    ("grand scribe", "Grand Scribe"),
                    ("grand treasurer", "Grand Treasurer"),
                    ("grand vice regent", "Grand Vice Regent"),
                    ("national director", "National Director"),
                    ("national officer", "National Officer"),
                    ("national operations manager", "National Operations Manager"),
                    (
                        "professional development director",
                        "Professional Development Director",
                    ),
                    ("regional director", "Regional Director"),
                    ("service director", "Service Director"),
                ],
                max_length=500,
                verbose_name="Who is allowed to vote on this ballot?",
            ),
        ),
        migrations.AlterField(
            model_name="ballotcomplete",
            name="role",
            field=models.CharField(
                choices=[
                    ("alumni programs director", "Alumni Programs Director"),
                    ("candidate chapter director", "Candidate Chapter Director"),
                    ("corresponding secretary", "Corresponding Secretary"),
                    ("council delegate", "Council Delegate"),
                    (
                        "educational foundation board of director",
                        "Educational Foundation Board Of Director",
                    ),
                    ("expansion director", "Expansion Director"),
                    ("grand inner guard", "Grand Inner Guard"),
                    ("grand marshal", "Grand Marshal"),
                    ("grand outer guard", "Grand Outer Guard"),
                    ("grand regent", "Grand Regent"),
                    ("grand scribe", "Grand Scribe"),
                    ("grand treasurer", "Grand Treasurer"),
                    ("grand vice regent", "Grand Vice Regent"),
                    ("national director", "National Director"),
                    ("national officer", "National Officer"),
                    ("national operations manager", "National Operations Manager"),
                    (
                        "professional development director",
                        "Professional Development Director",
                    ),
                    ("regent", "Regent"),
                    ("regional director", "Regional Director"),
                    ("scribe", "Scribe"),
                    ("service director", "Service Director"),
                    ("treasurer", "Treasurer"),
                    ("vice regent", "Vice Regent"),
                ],
                max_length=50,
            ),
        ),
    ]
