# Generated by Django 4.2.23 on 2026-09-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ballots", "0003_auto_20221022_1956"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballotcomplete",
            name="authority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chapter_vote", "The chapter voted"),
                    ("out_of_session", "Chapter out of session, Regent voted on its behalf"),
                ],
                default="",
                help_text="Only recorded for a chapter's vote; blank when a National Officer votes for themselves.",
                max_length=20,
                verbose_name="How the chapter's vote was decided",
            ),
        ),
    ]
