# Generated by Django 4.2.23 on 2026-09-09 05:38

from django.db import migrations
import thetatauCMT.ballots.models


class Migration(migrations.Migration):

    dependencies = [
        ("ballots", "0004_ballotcomplete_authority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="voters",
            field=thetatauCMT.ballots.models.MultiSelectField(
                choices=[
                    ("all_chapters", "All Chapters"),
                    ("all_candidate_chapters", "All Candidate Chapters"),
                    ("alumni programs director", "Alumni Programs Director"),
                    ("candidate chapter director", "Candidate Chapter Director"),
                    ("council delegate", "Council Delegate"),
                    ("educational foundation board of director", "Educational Foundation Board Of Director"),
                    ("expansion director", "Expansion Director"),
                    ("grand inner guard", "Grand Inner Guard"),
                    ("grand marshal", "Grand Marshal"),
                    ("grand outer guard", "Grand Outer Guard"),
                    ("grand regent", "Grand Regent"),
                    ("grand scribe", "Grand Scribe"),
                    ("grand treasurer", "Grand Treasurer"),
                    ("grand vice regent", "Grand Vice Regent"),
                    ("national director", "National Director"),
                    ("national officer", "National Officer"),
                    ("national operations manager", "National Operations Manager"),
                    ("professional development director", "Professional Development Director"),
                    ("regional director", "Regional Director"),
                    ("service director", "Service Director"),
                ],
                max_length=500,
                verbose_name="Who is allowed to vote on this ballot?",
            ),
        ),
    ]
