# Generated by Django 2.0.3 on 2018-06-15 18:31
import csv
from django.core.management import BaseCommand
from django.utils import timezone
from chapters.models import Chapter, GREEK_ABR


class Command(BaseCommand):
    # Show this when the user types help
    help = "Update chapter balances"

    def add_arguments(self, parser):
        parser.add_argument("file_path", nargs=1, type=str)

    # A command must define handle()
    def handle(self, *args, **options):
        balances = {}
        print(options["file_path"])
        with open(options["file_path"][0]) as csvfile:
            reader = csv.DictReader(csvfile)
            for row in reader:
                balance = row["Balance"].replace(",", "")
                chapter_name = row["Chapter"].lower()
                if chapter_name in GREEK_ABR:
                    chapter_name = GREEK_ABR[chapter_name]
                balances[chapter_name] = float(balance)
        for chapter in Chapter.objects.all():
            chapter.balance = balances.get(chapter.name.lower(), 0)
            chapter.balance_date = timezone.now()
            chapter.save()
