# Generated by Django 4.2.23 on 2026-08-01 02:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0008_taskdate_archived_taskdate_archived_on_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureArea",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier used by the registry fixture, e.g. 'events-attendance'. Do not rename.",
                        max_length=100,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "description",
                    models.TextField(help_text="Shown at the top of the catalog section.", verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome 6 class, e.g. 'fa-solid fa-calendar-days'.",
                        max_length=50,
                        verbose_name="Icon",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order in the catalog; lower sorts first.", verbose_name="Order"
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("member", "Member"),
                            ("officer", "Officer"),
                            ("natoff", "National Officer"),
                        ],
                        default="member",
                        help_text="Minimum audience needed to see this area at all.",
                        max_length=20,
                        verbose_name="Audience",
                    ),
                ),
                (
                    "feature_flag",
                    models.CharField(
                        blank=True,
                        help_text="Config key that must be enabled for this area to appear, e.g. 'FEATURE_AWARDS'.",
                        max_length=50,
                        verbose_name="Feature flag",
                    ),
                ),
                (
                    "has_tour",
                    models.BooleanField(
                        default=False, help_text="Whether a guided tour exists for this area.", verbose_name="Has tour"
                    ),
                ),
                (
                    "tour_entry_url_name",
                    models.CharField(
                        blank=True,
                        help_text="Named URL where this area's tour begins.",
                        max_length=200,
                        verbose_name="Tour entry URL name",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Uncheck to hide the area without deleting it.", verbose_name="Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature Area",
                "verbose_name_plural": "Feature Areas",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier used by the registry fixture. Do not rename.",
                        max_length=100,
                        unique=True,
                        verbose_name="Key",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "short_description",
                    models.CharField(
                        help_text="One-line copy for the catalog card.",
                        max_length=300,
                        verbose_name="Short description",
                    ),
                ),
                (
                    "long_description",
                    models.TextField(
                        blank=True,
                        help_text="Expanded help copy shown when the card is opened.",
                        verbose_name="Long description",
                    ),
                ),
                (
                    "url_name",
                    models.CharField(
                        blank=True,
                        help_text="Named URL to deep link to, namespaces included, e.g. 'forms:pledgeform' or 'viewflow:forms:hseducation:start'.",
                        max_length=200,
                        verbose_name="URL name",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="For features hosted outside this application. Cannot be combined with a URL name.",
                        max_length=500,
                        verbose_name="External URL",
                    ),
                ),
                (
                    "url_kwargs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Arguments for the named URL. Values may be the dynamic tokens '@chapter_slug', '@region_slug' or '@username', resolved per viewer.",
                        verbose_name="URL keyword arguments",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public", "Public"),
                            ("member", "Member"),
                            ("officer", "Officer"),
                            ("natoff", "National Officer"),
                        ],
                        help_text="Leave blank to inherit the area's audience.",
                        max_length=20,
                        verbose_name="Audience",
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Duty roles this feature belongs to, e.g. ['treasurer']. Targeting only, never access control.",
                        verbose_name="Roles",
                    ),
                ),
                (
                    "feature_flag",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to inherit the area's feature flag.",
                        max_length=50,
                        verbose_name="Feature flag",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Display order within the area; lower sorts first.", verbose_name="Order"
                    ),
                ),
                (
                    "released_at",
                    models.DateField(
                        blank=True,
                        help_text="Release date; drives the What's New feed.",
                        null=True,
                        verbose_name="Released",
                    ),
                ),
                (
                    "release_version",
                    models.CharField(
                        blank=True, help_text="e.g. '2026.03'.", max_length=20, verbose_name="Release version"
                    ),
                ),
                (
                    "is_highlighted",
                    models.BooleanField(
                        default=False, help_text="Show a NEW badge on the catalog card.", verbose_name="Highlighted"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide the feature without deleting it.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="guides.featurearea",
                        verbose_name="Area",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="The recurring obligation this feature satisfies, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="features",
                        to="tasks.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
                "ordering": ["area__order", "order", "name"],
            },
        ),
    ]
