# Generated by Django 4.2.23 on 2026-08-01 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("guides", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Step sequence within the area's tour; lower runs first.",
                        verbose_name="Order",
                    ),
                ),
                (
                    "selector",
                    models.CharField(
                        blank=True,
                        help_text="CSS selector for the element to highlight, e.g. '[data-tour=\"nav-activity\"]'. Leave blank for a centered step with no highlight.",
                        max_length=200,
                        verbose_name="Selector",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "side",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("top", "Top"),
                            ("right", "Right"),
                            ("bottom", "Bottom"),
                            ("left", "Left"),
                            ("over", "Over"),
                        ],
                        help_text="Where the popover sits relative to the element.",
                        max_length=10,
                        verbose_name="Side",
                    ),
                ),
                (
                    "align",
                    models.CharField(
                        blank=True,
                        choices=[("start", "Start"), ("center", "Center"), ("end", "End")],
                        max_length=10,
                        verbose_name="Align",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("public", "Public"),
                            ("member", "Member"),
                            ("officer", "Officer"),
                            ("natoff", "National Officer"),
                        ],
                        help_text="Leave blank to inherit the area's audience.",
                        max_length=20,
                        verbose_name="Audience",
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Show this step only to holders of these duty roles. Empty shows it to everyone.",
                        verbose_name="Roles",
                    ),
                ),
                (
                    "feature_flag",
                    models.CharField(
                        blank=True,
                        help_text="Skip this step when the flag is off. The area's own flag is already checked.",
                        max_length=50,
                        verbose_name="Feature flag",
                    ),
                ),
                (
                    "url_name",
                    models.CharField(
                        blank=True,
                        help_text="Named URL of the page this step belongs to. Reserved for future cross-page chaining.",
                        max_length=200,
                        verbose_name="URL name",
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_steps",
                        to="guides.featurearea",
                        verbose_name="Area",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        help_text="The catalog entry this step introduces, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tour_steps",
                        to="guides.feature",
                        verbose_name="Feature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tour Step",
                "verbose_name_plural": "Tour Steps",
                "ordering": ["area__order", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserTourCompletion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Completed"), ("dismissed", "Dismissed")],
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now=True, verbose_name="Completed at")),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="guides.featurearea",
                        verbose_name="Area",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_completions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Tour Completion",
                "verbose_name_plural": "User Tour Completions",
                "ordering": ["-completed_at"],
                "unique_together": {("user", "area")},
            },
        ),
    ]
