# Generated by Django 4.2.23 on 2026-08-01 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("guides", "0002_tourstep_usertourcompletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAcknowledgement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField(verbose_name="Object ID")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("modal", "What's New modal"),
                            ("badge", "NEW badge"),
                            ("visited", "Followed the link"),
                            ("bulk", "Dismissed all"),
                        ],
                        help_text="Which affordance the user used. Feeds the adoption metrics.",
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True, verbose_name="Acknowledged at")),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(("app_label", "guides"), ("model", "feature")),
                            models.Q(("app_label", "announcements"), ("model", "announcement")),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Acknowledgement",
                "verbose_name_plural": "User Acknowledgements",
                "ordering": ["-acknowledged_at"],
                "indexes": [models.Index(fields=["user", "content_type"], name="guides_user_user_id_f910ec_idx")],
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
    ]
