# Generated by Django 4.2.23 on 2026-08-01 06:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_taskdate_archived_taskdate_archived_on_and_more"),
        ("guides", "0003_useracknowledgement"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleGuide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("adviser", "Adviser"),
                            ("alumni programs director", "Alumni Programs Director"),
                            ("board member", "Board Member"),
                            ("candidate chapter director", "Candidate Chapter Director"),
                            ("committee chair", "Committee Chair"),
                            ("corresponding secretary", "Corresponding Secretary"),
                            ("council delegate", "Council Delegate"),
                            ("diversity, equity, and inclusion chair", "Diversity, Equity, And Inclusion Chair"),
                            ("educational foundation board of director", "Educational Foundation Board Of Director"),
                            ("employer/ee", "Employer/Ee"),
                            ("events chair", "Events Chair"),
                            ("expansion director", "Expansion Director"),
                            ("faculty adviser", "Faculty Adviser"),
                            ("fundraising chair", "Fundraising Chair"),
                            ("grand inner guard", "Grand Inner Guard"),
                            ("grand marshal", "Grand Marshal"),
                            ("grand outer guard", "Grand Outer Guard"),
                            ("grand regent", "Grand Regent"),
                            ("grand scribe", "Grand Scribe"),
                            ("grand treasurer", "Grand Treasurer"),
                            ("grand vice regent", "Grand Vice Regent"),
                            ("house corporation president", "House Corporation President"),
                            ("house corporation treasurer", "House Corporation Treasurer"),
                            ("housing chair", "Housing Chair"),
                            ("marshal", "Marshal"),
                            ("national director", "National Director"),
                            ("national officer", "National Officer"),
                            ("national operations manager", "National Operations Manager"),
                            ("other appointee", "Other Appointee"),
                            ("parent", "Parent"),
                            ("pd chair", "Pd Chair"),
                            ("pledge/new member educator", "Pledge/New Member Educator"),
                            ("professional development director", "Professional Development Director"),
                            ("project chair", "Project Chair"),
                            ("recruitment chair", "Recruitment Chair"),
                            ("regent", "Regent"),
                            ("regional director", "Regional Director"),
                            ("risk management chair", "Risk Management Chair"),
                            ("rube goldberg chair", "Rube Goldberg Chair"),
                            ("scholarship chair", "Scholarship Chair"),
                            ("scribe", "Scribe"),
                            ("service chair", "Service Chair"),
                            ("service director", "Service Director"),
                            ("social/brotherhood chair", "Social/Brotherhood Chair"),
                            ("treasurer", "Treasurer"),
                            ("vice regent", "Vice Regent"),
                            ("website/social media chair", "Website/Social Media Chair"),
                        ],
                        help_text="Duty role this guide is for. Must match tasks.Task.owner exactly.",
                        max_length=50,
                        unique=True,
                        verbose_name="Role",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL segment; set automatically from the role.",
                        max_length=60,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Title")),
                (
                    "summary",
                    models.TextField(
                        help_text="Two to four sentences orienting someone who just took the office.",
                        verbose_name="Summary",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Order")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Role Guide",
                "verbose_name_plural": "Role Guides",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="RoleGuideStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveSmallIntegerField(default=0, verbose_name="Order")),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("body", models.TextField(blank=True, verbose_name="Body")),
                (
                    "cadence",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("once", "Once, when you take office"),
                            ("each_term", "Every term"),
                            ("annual", "Once a year"),
                            ("ongoing", "Ongoing"),
                        ],
                        max_length=20,
                        verbose_name="Cadence",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        blank=True,
                        help_text="Catalog entry this step sends the officer to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_guide_steps",
                        to="guides.feature",
                        verbose_name="Feature",
                    ),
                ),
                (
                    "guide",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="guides.roleguide",
                        verbose_name="Guide",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Recurring obligation, so the step can show live due dates.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_guide_steps",
                        to="tasks.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Guide Step",
                "verbose_name_plural": "Role Guide Steps",
                "ordering": ["guide__order", "order", "id"],
            },
        ),
    ]
