# Generated by Django 4.2.23 on 2026-08-02 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0005_feature_url_fragment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usertourcompletion",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="usertourcompletion",
            name="area",
        ),
        migrations.RemoveField(
            model_name="usertourcompletion",
            name="user",
        ),
        migrations.RemoveField(
            model_name="featurearea",
            name="has_tour",
        ),
        migrations.RemoveField(
            model_name="featurearea",
            name="tour_entry_url_name",
        ),
        migrations.DeleteModel(
            name="TourStep",
        ),
        migrations.DeleteModel(
            name="UserTourCompletion",
        ),
    ]
