# Generated by Django 4.2.23 on 2026-07-23 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contact_sync", "0002_auto_sync_scopes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercontactsynctoken",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="usercontactsynctoken",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
