volumes:
  thetataucmt_local_postgres_data: {}
  thetataucmt_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: thetataucmt_local_django
    container_name: thetataucmt_local_django
    depends_on:
      - postgres
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000" # webserver
      - "8888:8888" # ipython notebook
      - "5678:5678" # Debugger
    command: /start

  postgres:
    image: postgres:12.6@sha256:26ce5e265fbbf120b4a89a9b26770bad757a7dfa4f329038d93770edbe5aae00
    container_name: thetataucmt_local_postgres
    volumes:
      - thetataucmt_local_postgres_data:/var/lib/postgresql/data
      - thetataucmt_local_postgres_data_backups:/backups
    ports:
      - "5435:5435"
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:v1.31.0@sha256:c96991d9bef73594c246d89ca81411d4e916f03e76a7d2d72fa2ab5dd3c9ce24
    container_name: thetataucmt_local_mailpit
    ports:
      - "8025:8025"
