# Generated by Django 2.0.3 on 2018-06-14 18:26

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
        ('address', '0002_auto_20160213_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Balance chapter owes.', max_digits=7)),
                ('tax', models.PositiveIntegerField(help_text='Tax number, if chapter participates in group exemption.')),
                ('greek', models.CharField(blank=True, help_text='Greek letter abbreviation', max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('school', models.CharField(blank=True, max_length=50)),
                ('address', address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address', unique=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='regions.Region')),
            ],
        ),
    ]
