# Generated by Django 2.0.3 on 2018-06-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='tax',
            field=models.PositiveIntegerField(blank=True, help_text='Tax number, if chapter participates in group exemption.', null=True, unique=True),
        ),
    ]
