# Generated by Django 2.2.12 on 2020-05-17 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("regions", "0001_initial"),
        ("chapters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chapters",
                to="regions.Region",
            ),
        ),
    ]
