# Generated by Django 2.2.12 on 2020-05-17 17:27

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0002_chapter_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="address",
            field=address.models.AddressField(
                blank=True,
                help_text="We periodically need to mail things (shingles, badges, etc) to your chapter.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.Address",
                verbose_name="Mailing Address",
            ),
        ),
    ]
