# Generated by Django 2.0.3 on 2018-06-15 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0002_auto_20180614_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='balance_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='greek',
            field=models.CharField(blank=True, help_text='Greek letter abbreviation', max_length=10),
        ),
    ]
