# Generated by Django 2.2.12 on 2020-09-23 03:16
import datetime
from django.utils import timezone
from django.db import migrations, models


def set_modified(apps, schema_editor):
    chapter = apps.get_model("chapters", "Chapter")
    for field in chapter._meta.local_fields:
        if hasattr(field, "auto_now"):
            field.auto_now = False
    past_date = datetime.datetime(2018, 1, 1) + timezone.timedelta(days=1)
    for chapter in chapter.objects.all():
        chapter_report = chapter.info.last()
        last_modified = past_date
        if chapter_report:
            last_modified = chapter_report.modified
        chapter.modified = last_modified
        chapter.save(update_fields=["modified"])


def unset_modified(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0003_auto_20200517_1027"),
        ("forms", "0002_auto_20200517_1020"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(set_modified, unset_modified),
    ]
