# Generated by Django 2.0.3 on 2018-06-15 16:54
import os
import csv
from django.utils import timezone
from django.db import migrations


def load_chapters(apps, schema_editor):
    chapter = apps.get_model("chapters", "Chapter")
    region = apps.get_model("regions", "Region")
    with open(f'{os.path.split(__file__)[0]}/data_initial.csv', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for id_obj, row in enumerate(reader):
            region_obj = region.objects.get(name=row["region"])
            tax_val = None
            if row["tax"] != "":
                tax_val = int(row["tax"])
            chapter_obj = chapter(
                id=id_obj,
                name=row["name"],
                region=region_obj,
                email=row["email"],
                address={'city': row["city"],
                         'state': row["state"],
                         'country': row["country"]},
                balance=float(row["balance"]),
                balance_date=timezone.now(),
                tax=tax_val,
                greek=row["greek"],
                school=row["school"],
            )
            chapter_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0003_auto_20180615_0952'),
        ('regions', '0002_initial_regions_data'),
    ]

    operations = [
        migrations.RunPython(load_chapters),
    ]
