# Generated by Django 2.0.3 on 2018-06-15 21:45

from django.db import migrations, models
from django.utils.text import slugify


def migrate_data_forward(apps, schema_editor):
    chapter = apps.get_model("chapters", "Chapter")
    for instance in chapter.objects.all():
        print(f"Generating slug for {instance}")
        instance.slug = slugify(instance.name)
        instance.save()  # Will trigger slug update


def migrate_data_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0004_initial_chapters_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(default=None, null=True, unique=True),
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_backward)
    ]
