# Generated by Django 2.2.12 on 2020-10-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0004_chapter_modified"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaptercurricula",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
