# Generated by Django 2.0.3 on 2018-07-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0005_chapter_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['name']},
        ),
    ]
