# Generated by Django 2.0.3 on 2018-08-11 04:38

from django.db import migrations, models


QUARTER_SCHOOLS = [
    'Epsilon Delta',
    'Omicron Gamma',
    'Pi Delta',
    'Upsilon Delta',
    'Sigma Delta',
    'SCU Colony',
    'UCSB Colony',
    'Victoria Colony',
]


def add_quarter_schools(apps, schema_editor):
    chapter = apps.get_model("chapters", "Chapter")
    for chapter_name in QUARTER_SCHOOLS:
        chapter_obj = chapter.objects.get(name=chapter_name)
        chapter_obj.school_type = 'quarter'
        chapter_obj.save()


def delete():
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_auto_20180705_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='school_type',
            field=models.CharField(choices=[('semester', 'Semester'), ('quarter', 'Quarter')], default='semester', max_length=10),
        ),
        migrations.RunPython(add_quarter_schools, delete),
    ]
