# Generated by Django 2.2.12 on 2021-09-11 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0007_chapter_house"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chapter",
            old_name="colony",
            new_name="candidate_chapter",
        ),
    ]
