# Generated by Django 2.0.3 on 2018-09-10 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0008_auto_20180908_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterCurricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curricula', to='chapters.Chapter')),
            ],
        ),
    ]
