# Generated by Django 2.0.3 on 2019-02-22 16:46
"""
Lat longs comes from geopy and https://www.latlong.net/
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="Theta Tau CMT")
location = geolocator.geocode(chapter.school)
"""

from django.db import migrations, models


lat_longs = {
     'Alpha': (44.97308605, -93.2370881262941),
     'Beta': (47.1099114, -88.5511513291051),
     'Chi': (33.45205165, -112.063678942176),
     'Chi Beta': (41.64127495, -83.5968356357202),
     'Chi Delta': (38.4219142, -82.4433735),
     'Chi Gamma': (35.9542493, -83.9307395),
     'CSLB Colony': (33.7817465, -118.11520123952),
     'Delta': (41.50138695, -81.6007021615902),
     'Delta Gamma': (33.4206602, -111.932634924965),
     'Drexel Colony': (39.9574, -75.1902670552555),
     'Epsilon': (37.8687126, -122.255868148743),
     'Epsilon Beta': (42.35369115, -83.0724851791387),
     'Epsilon Delta': (32.87935255, -117.231100493855),
     'Eta': (42.3583961, -71.0956778766393),
     'Eta Epsilon': (43.66213935, -70.2752196593726),
     'FIT Colony': (28.0642296, -80.6230097241205),
     'Gamma Beta': (38.9044038, -77.047803410814),
     'Iota Delta': (36.14422155, -86.802757257693),
     'Iota Epsilon': (33.9404278, -83.373049049883),
     'Iota Gamma': (39.1318525, -84.5157620959388),
     'JMU Colony': (38.43399425, -78.8581617061257),
     'Kappa': (40.0951385, -88.240006594676),
     'Kappa Beta': (33.46433105, -88.7994254571275),
     'Kappa Delta': (42.4505507, -76.4783512955428),
     'Kappa Epsilon': (34.0224149, -118.286344073446),
     'Kappa Gamma': (37.548215, -77.4530642444471),
     'Lambda Beta': (36.1748745, -85.5089052663721),
     'Lambda Delta': (37.98042375, -121.312847198327),
     'Lambda Epsilon': (32.7726805, -117.18897659618),
     'Lambda Gamma': (34.66869155, -82.837434756078),
     'Mu': (33.21208215, -87.5396740151865),
     'Mu Delta': (37.36566745, -120.421588883632),
     'Mu Epsilon': (30.4255147, -97.7042754),
     'Mu Gamma': (42.901646, -78.8683495353673),
     'NJIT Colony': (40.7423025, -74.1792817237128),
     'Nu Delta': (40.44415295, -79.9624399276271),
     'Nu Epsilon': (29.94121955, -90.1201008917919),
     'Nu Gamma': (42.0897359, -75.970203),
     'Omega': (44.0739534, -103.205657925677),
     'Omega Beta': (40.71703345, -73.599835005538),
     'Omega Delta': (35.1289696, -89.9802249790913),
     'Omega Gamma': (25.75533775, -80.3762889746807),
     'Omicron': (41.6659, -91.573103065),
     'Omicron Beta': (42.3172294, -83.2319393553883),
     'Omicron Delta': (40.47913175, -74.431688684404),
     'Omicron Epsilon': (35.1851087, -111.655837039036),
     'Omicron Gamma': (38.5336349, -121.790772639747),
     'Phi': (40.4319722, -86.923893679845),
     'Phi Delta': (30.44235995, -84.2974786716626),
     'Phi Gamma': (36.1295801, -97.0885371469736),
     'Pi': (38.0353682, -78.5035322),
     'Pi Delta': (33.6431901, -117.84016493553),
     'Psi Beta': (30.284151, -97.7319559808022),
     'Psi Delta': (42.3504253, -71.1005611418395),
     'Psi Gamma': (37.21872455, -80.4254251869494),
     'Rho': (35.77184965, -78.6740869545263),
     'Rho Beta': (39.3235304, -82.100107040962),
     'Rho Delta': (39.5469449, -119.813465660936),
     'Rho Gamma': (28.59899755, -81.1971250118395),
     'ROW Colony': (39.7103526, -75.1193266647699),
     'SCU Colony': (37.3485345, -121.936442006552),
     'Sigma': (40.00570905, -83.0286625976912),
     'Sigma Delta': (33.97127125, -117.337787518449),
     'Sigma Gamma': (41.8295635, -71.416277),
     'Tau': (43.01890185, -76.1191814762468),
     'Tau Beta': (32.84180115, -96.7815281014706),
     'Tau Delta': (39.51100865, -84.7292977026307),
     'Tau Gamma': (39.9492344, -75.191989851901),
     'Theta Delta': (39.2964392, -76.592394032674),
     'Theta Gamma': (42.2942142, -83.710038935096),
     'TU Colony': (39.95472495, -75.1534690525548),
     'UA Colony': (42.68435875, -73.8258342304267),
     'UCSB Colony': (34.4145937, -119.84581949869),
     'UNH Colony': (41.2912226, -72.9612122),
     'Upsilon': (36.065152, -94.176095339117),
     'Upsilon Beta': (36.885682, -76.3076857937011),
     'Upsilon Delta': (34.07088865, -118.446731966638),
     'Upsilon Gamma': (28.0597757, -82.4181673),
     'UW Colony': (47.6543238, -122.308008943203),
     'Victoria Colony': (48.46205995, -123.311419806048),
     'Xi': (44.02519995, -88.5510866732877),
     'Xi Delta': (38.83931995, -77.3114844299214),
     'Xi Gamma': (30.5518161, -96.2435993128747),
     'Zeta': (38.9538529, -95.2631378617998),
     'Zeta Delta': (33.9928298, -81.0268516781225),
     'Zeta Epsilon': (40.9098347, -73.1211991145776),
     'Zeta Gamma': (29.6328784, -82.3490133048243),
     'CSF Colony': (33.88628, -117.92437),
     'Eta Delta': (38.986629, -76.956017),
     'Eta Gamma': (40.01049, -105.27684),
     'Pi Gamma': (35.315681, -80.679314),
     'Theta Epsilon': (40.85102, -73.90453),
     'Xi Beta': (41.05999, -80.04362)}


def add_lat_longs(apps, schema_editor):
    chapter = apps.get_model("chapters", "Chapter")
    for chapter_name, lat_long in lat_longs.items():
        try:
            chapter_obj = chapter.objects.get(name=chapter_name)
        except chapter.DoesNotExist:
            print(f"Chapter does not exist {chapter_name}")
        else:
            chapter_obj.latitude, chapter_obj.longitude = lat_long
            chapter_obj.save()


def delete(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0010_initial_curricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.RunPython(add_lat_longs, delete),
    ]
