# Generated by Django 2.2.3 on 2019-08-13 00:54

from django.db import migrations, models


def check_colony(apps, schema_editor):
    chapter = apps.get_model("chapters", "Chapter")
    for chapter in chapter.objects.all():
        if 'colony' in chapter.name.lower():
            chapter.colony = True
            chapter.save()


def delete(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0011_auto_20190222_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='colony',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(check_colony, delete),
    ]
