# Generated by Django 3.2.15 on 2025-12-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0013_chapter_nme_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='founding_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='misc_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chapter',
            name='recharter_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
