# Generated by Django 2.2.3 on 2019-12-27 18:45

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0013_auto_20191110_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='council',
            field=models.CharField(default='none', help_text="The name of the council of which your Chapter is a member, for example the IFC or PFC.  Please write 'none' if you are not recognized as a Fraternity or not a member of a council.", max_length=55, verbose_name='Name of Council'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='recognition',
            field=models.CharField(choices=[('fraternity', 'Recognized as a Fraternity'), ('org', 'Recognized as a Student Organization NOT a Fraternity'), ('other', 'Recognized but not as a Fraternity or Student Organization'), ('not', 'Not Recognized by University')], default='not', help_text='Please indicate if your chapter is recognized by your host college or university.', max_length=10, verbose_name='University Recognition'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='address',
            field=address.models.AddressField(blank=True, help_text='We periodically need to mail things (shingles, badges, etc) to your chapter.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address', unique=True, verbose_name='Mailing Address'),
        ),
    ]
