# Generated by Django 2.2.3 on 2019-12-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0014_auto_20191227_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='recognition',
            field=models.CharField(choices=[('fraternity', 'Recognized as a Fraternity'), ('org', 'Recognized as a Student Organization NOT a Fraternity'), ('other', 'Recognized but not as a Fraternity or Student Organization'), ('not_rec', 'Not Recognized by University')], default='not_rec', help_text='Please indicate if your chapter is recognized by your host college or university.', max_length=10, verbose_name='University Recognition'),
        ),
    ]
