# Generated by Django 3.2.15 on 2026-03-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0014_auto_20251219_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Sometimes the address is not sufficient and you need a second line for the address. This is not a separate address, just an additional line for the main address. For example, you may need to include a building name or a specific person to receive the mail.', max_length=100, verbose_name='Mailing Address Line 2'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='instagram',
            field=models.URLField(blank=True, help_text='You must include the full URL including https:// or http://'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='linkedin',
            field=models.URLField(blank=True, help_text='You must include the full URL including https:// or http://'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='tiktok',
            field=models.URLField(blank=True, help_text='You must include the full URL including https:// or http://'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='twitter',
            field=models.URLField(blank=True, help_text='You must include the full URL including https:// or http://'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='youtube',
            field=models.URLField(blank=True, help_text='You must include the full URL including https:// or http://'),
        ),
    ]
