# Generated by Django 4.2.23 on 2026-07-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0015_add_address_socials_to_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="recognition_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Please insert the URL to that office's website here.",
                max_length=255,
                verbose_name="Recognizing Office Website",
            ),
        ),
    ]
