# Generated by Django 2.2.3 on 2020-01-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0015_auto_20191230_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='facebook',
            field=models.URLField(blank=True, help_text='You must include the full URL including https:// or http://'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='website',
            field=models.URLField(blank=True, help_text='You must include the full URL including https:// or http://'),
        ),
    ]
