# Generated by Django 4.2.23 on 2026-07-28 20:10

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0016_chapter_recognition_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="size_target",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The target membership size for the chapter to strive for.",
                null=True,
                verbose_name="Membership Size Target",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="support_specialist",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                default="",
                help_text="The staff member(s) who support this chapter. Rich text is supported.",
                verbose_name="Support Specialist",
            ),
        ),
    ]
