# Generated by Django 2.2.12 on 2022-06-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="central_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
