# Generated by Django 2.2.3 on 2019-08-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='estimate',
            field=models.BooleanField(default=False),
        ),
    ]
