# Generated by Django 2.0.3 on 2018-06-15 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180614_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='TEST1311', help_text='Combination of badge number and chapter abbr, eg. X1311', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.PositiveIntegerField(default=2018, help_text='Use the following format: YYYY', validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2028)]),
        ),
    ]
