# Generated by Django 2.2.12 on 2020-08-27 03:21

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200517_1027"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user", managers=[("objects", users.models.CustomUserManager()),],
        ),
    ]
