# Generated by Django 2.0.3 on 2018-06-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180615_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chapter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chapters.Chapter'),
            preserve_default=False,
        ),
    ]
