# Generated by Django 2.2.12 on 2020-10-03 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_auto_20200903_2152"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(default=datetime.date(1904, 10, 15)),
        ),
        migrations.AddField(
            model_name="user",
            name="email_school",
            field=models.EmailField(
                default="test@thetatau.org",
                help_text="We will send an acknowledgement message. (ends in .edu)",
                max_length=254,
                verbose_name="School Email",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Full Middle Name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True,
                help_text="If different than your first name - eg Buddy, Skip, or Mike. Do NOT indicate 'pledge names'",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="suffix",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Suffix (such as Jr., III)"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mr", "Mr."),
                    ("miss", "Miss"),
                    ("ms", "Ms"),
                    ("mrs", "Mrs"),
                    ("mx", "Mx"),
                    ("none", ""),
                ],
                max_length=5,
                verbose_name="Title",
            ),
        ),
    ]
