# Generated by Django 2.0.3 on 2018-06-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180615_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
