# Generated by Django 2.2.12 on 2020-10-03 15:13

from django.db import migrations, models
import django.db.models.deletion


def str_to_major(apps, schema_editor):
    users = apps.get_model("users", "User")
    curricula = apps.get_model("chapters", "ChapterCurricula")
    total = users.objects.all().count()
    for count, user in enumerate(users.objects.all()):
        print(f"Processing {count + 1}/{total}")
        chapter = user.chapter
        try:
            major, created = curricula.objects.get_or_create(
                chapter=chapter,
                major__iexact=user.major_str.lower(),
                defaults=dict(major=user.major_str, approved=False),
            )
        except curricula.MultipleObjectsReturned:
            major = curricula.objects.filter(
                chapter=chapter, major__iexact=user.major_str.lower()
            ).first()
        user.major = major
        user.save()


def major_to_str(apps, schema_editor):
    users = apps.get_model("users", "User")
    for user in users.objects.all():
        major = user.major.major
        user.major_str = major
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20201002_2213"),
        ("chapters", "0005_chaptercurricula_approved"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="major", new_name="major_str"
        ),
        migrations.AddField(
            model_name="user",
            name="major",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_NULL,
                blank=True,
                null=True,
                related_name="user",
                to="chapters.ChapterCurricula",
            ),
        ),
        migrations.RunPython(str_to_major, major_to_str),
        migrations.RemoveField(
            model_name="user",
            name="major_str",
        ),
    ]
