# Generated by Django 2.0.3 on 2018-06-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_initial_users_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chapters.Chapter'),
        ),
    ]
