# Generated by Django 2.0.3 on 2018-07-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180615_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='user',
            name='employer_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='employer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
