# Generated by Django 2.2.12 on 2020-12-08 04:37

import address.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_auto_20160213_1726"),
        ("users", "0008_auto_20201108_0934"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="address"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="deceased",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="degree",
            field=models.CharField(
                choices=[
                    ("bs", "Bachelor of Science"),
                    ("ms", "Master of Science"),
                    ("mba", "Master of Business Administration"),
                    ("phd", "Doctor of Philosophy"),
                    ("ba", "Bachelor of Arts"),
                    ("ma", "Master of Arts"),
                    ("me", "Master of Engineering"),
                    ("none", "None"),
                ],
                default="bs",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_first_name",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Emergency Contact first name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_last_name",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Emergency Contact last name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_middle_name",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Emergency Contact Middle Name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_nickname",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Emergency Contact nickname name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Format: 9999999999 no spaces, dashes, etc.",
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="emergency_relation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("parent", "Parent"),
                    ("guardian", "Guardian"),
                    ("grandparent", "Grandparent"),
                    ("partner", "Spouse/Partner"),
                    ("sibling", "Sibling (over 18)"),
                    ("other", "Other relative"),
                    ("friend", "Friend"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employer_address",
            field=address.models.AddressField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employer",
                to="address.Address",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employer_changed",
            field=model_utils.fields.MonitorField(
                default=django.utils.timezone.now, monitor="employer"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="maiden_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Maiden Name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="no_contact",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="employer_position",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="graduation_year",
            field=models.PositiveIntegerField(
                default=2020,
                help_text="Use the following format: YYYY",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2030),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userstatuschange",
            name="status",
            field=models.CharField(
                choices=[
                    ("alumni", "alumni"),
                    ("alumnipend", "alumni pending"),
                    ("active", "active"),
                    ("activepend", "active pending"),
                    ("pnm", "prospective"),
                    ("away", "away"),
                    ("depledge", "depledge"),
                    ("advisor", "advisor"),
                    ("nonmember", "nonmember"),
                    ("resigned", "resigned"),
                    ("expelled", "expelled"),
                    ("friend", "friend"),
                ],
                max_length=10,
            ),
        ),
    ]
