# Generated by Django 2.2.12 on 2021-01-19 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_auto_20201207_2137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="graduation_year",
            field=models.PositiveIntegerField(
                default=2021,
                help_text="Use the following format: YYYY",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2031),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usersemestergpa",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                    (2024, 2024),
                    (2025, 2025),
                    (2026, 2026),
                    (2027, 2027),
                    (2028, 2028),
                ],
                default=2021,
            ),
        ),
        migrations.AlterField(
            model_name="usersemesterservicehours",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                    (2024, 2024),
                    (2025, 2025),
                    (2026, 2026),
                    (2027, 2027),
                    (2028, 2028),
                ],
                default=2021,
            ),
        ),
    ]
