# Generated by Django 2.2.12 on 2021-07-26 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_year_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDemographic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("not_listed", "An identity not listed (write-in)"),
                            ("agender", "Agender"),
                            ("cisgender", "Cisgender"),
                            ("female", "Female"),
                            ("genderqueer", "Genderqueer/Gender non-conforming"),
                            ("intersex", "Intersex"),
                            ("male", "Male"),
                            ("nonbinary", "Nonbinary"),
                            ("no_answer", "Prefer not to answer"),
                            ("trans_male", "Trans man/Trans male"),
                            ("trans_female", "Trans woman/Trans female"),
                        ],
                        default="no_answer",
                        max_length=105,
                        null=True,
                        verbose_name="How would you describe your gender identity? (Select all that apply)",
                    ),
                ),
                (
                    "gender_write",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Gender identity write-in",
                    ),
                ),
                (
                    "sexual",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("asexual", "Asexual"),
                            ("bisexual", "Bisexual"),
                            ("not_listed", "An identity not listed (write-in)"),
                            ("heterosexual", "Heterosexual / straight"),
                            ("homosexual", "Homosexual / gay / lesbian"),
                            ("no_answer", "Prefer not to answer"),
                            ("queer", "Queer"),
                        ],
                        default="no_answer",
                        max_length=67,
                        null=True,
                        verbose_name="How would you describe your sexual identity? (Select all that apply)",
                    ),
                ),
                (
                    "sexual_write",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Sexual identity write-in",
                    ),
                ),
                (
                    "racial",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("asian", "Asian"),
                            ("black", "Black or African American"),
                            ("caucasian", "Caucasian / White"),
                            ("islander", "Native Hawaiiain or Other Pacific Islander"),
                            ("middle_eastern", "Middle Eastern or North African"),
                            ("not_listed", "An identity not listed (write-in)"),
                            ("latinx", "Latinx or Hispanic"),
                            ("mixed", "Mixed race"),
                            ("native", "Native American / First Nations"),
                            ("no_answer", "Prefer not to answer"),
                        ],
                        default="no_answer",
                        max_length=86,
                        null=True,
                        verbose_name="With which racial and ethnic group(s) do you identify? (Select all that apply)",
                    ),
                ),
                (
                    "racial_write",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Racial and ethnic identity write-in",
                    ),
                ),
                (
                    "specific_ethnicity",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Please print your specific ethnicities. Examples of ethnicities include (for example): German, Korean, Midwesterner (American), Mexican American, Navajo Nation, Samoan, Puerto Rican, Southerner (American), Chinese, etc. Note, you may report more that one group.",
                    ),
                ),
                (
                    "ability",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("sensory", "A sensory impairment (vision or hearing)"),
                            ("learning", "A learning disability (eg. ADHD, dyslexia)"),
                            (
                                "medical",
                                "A long-term medical illness (eg. epilepsy, cystic fibrosis)",
                            ),
                            ("mobility", "A mobility impairment"),
                            ("mental", "A mental health disorder"),
                            (
                                "temp",
                                "A temporary impairment due to illness or injury (eg. broken ankle, surgery)",
                            ),
                            (
                                "no_impairment",
                                "I do not identify with a disability or impairment",
                            ),
                            (
                                "not_listed",
                                "A disability or impairment not listed (write-in)",
                            ),
                            ("no_answer", "Prefer not to answer"),
                        ],
                        default="no_answer",
                        max_length=80,
                        null=True,
                        verbose_name="How do you describe your disability / ability status? We are interested in this identification regardless of whether you typically request accommodations for this disability.",
                    ),
                ),
                (
                    "ability_write",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Disability or impairment write-in",
                    ),
                ),
                (
                    "first_gen",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        verbose_name="Are you a first-generation college student?",
                    ),
                ),
                (
                    "english",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")],
                        default=False,
                        verbose_name="Is English your first language?",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demographic",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
