# Generated by Django 2.0.3 on 2018-08-20 02:42
from django.db import migrations, models


old_new = {
    'secretary': 'scribe',
    'vice president': 'vice regent',
    'president': 'regent',
    'other adviser': 'adviser',
    'alumni adviser': 'adviser',
    'build chair': 'project chair',
    'chapter officer': 'other appointee',
}


def adjust_roles(apps, schema_editor):
    role = apps.get_model("users", "UserRoleChange")
    roles = role.objects.all()
    for role_obj in roles:
        role_name = role_obj.role.lower()
        if role_obj.role in ['vice-regent',
                             'alumni-adviser', 'board-member',
                             'corresponding-secretary']:
            # Accidentally added bad roles; remove those
            role_obj.delete()
            continue
        elif role_name in old_new:
            role_obj.role = old_new[role_name]
        else:
            role_obj.role = role_name
        role_obj.save()
        if role.objects.filter(
            role=role_obj.role, user=role_obj.user,
            start=role_obj.start, end=role_obj.end
                               ).count() > 1:
            print(f"Deleting: {role_obj}")
            role_obj.delete()


def delete(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_initial_service_gpa_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolechange',
            name='role',
            field=models.CharField(choices=[('adviser', 'Adviser'), ('board member', 'Board Member'), ('committee chair', 'Committee Chair'), ('corresponding secretary', 'Corresponding Secretary'), ('employer/ee', 'Employer/Ee'), ('faculty adviser', 'Faculty Adviser'), ('fundraising chair', 'Fundraising Chair'), ('house corporation president', 'House Corporation President'), ('house corporation treasurerhousing chair', 'House Corporation Treasurerhousing Chair'), ('national director', 'National Director'), ('national officer', 'National Officer'), ('other appointee', 'Other Appointee'), ('parent', 'Parent'), ('pd chair', 'Pd Chair'), ('pledge/new member educator', 'Pledge/New Member Educator'), ('president', 'President'), ('project chair', 'Project Chair'), ('recruitment chair', 'Recruitment Chair'), ('regent', 'Regent'), ('regional director', 'Regional Director'), ('risk management chair', 'Risk Management Chair'), ('rube goldberg chair', 'Rube Goldberg Chair'), ('rush chair', 'Rush Chair'), ('scholarship chair', 'Scholarship Chair'), ('scribe', 'Scribe'), ('secretary', 'Secretary'), ('service chair', 'Service Chair'), ('social/brotherhood chair', 'Social/Brotherhood Chair'), ('treasurer', 'Treasurer'), ('vice president', 'Vice President'), ('vice regent', 'Vice Regent'), ('website/social media chair', 'Website/Social Media Chair')], max_length=50),
        ),
        migrations.RunPython(adjust_roles, delete),
    ]
