# Generated by Django 2.0.3 on 2018-08-24 02:56

from django.db import migrations
from core.models import forever


def fix_alumni_status(apps, schema_editor):
    status = apps.get_model("users", "UserStatusChange")
    for status_obj in status.objects.all():
        if status_obj.status == 'alumni':
            # Grad date set at end, should be start
            status_obj.start = status_obj.end
            status_obj.end = forever()
        status_obj.save()


def delete(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180819_1942'),
    ]

    operations = [
        migrations.RunPython(fix_alumni_status, delete),
    ]
