# Generated by Django 2.2.12 on 2021-07-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_userdemographic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdemographic",
            name="english",
            field=models.BooleanField(
                blank=True,
                choices=[(None, ""), (True, "Yes"), (False, "No")],
                default=None,
                null=True,
                verbose_name="Is English your first language?",
            ),
        ),
        migrations.AlterField(
            model_name="userdemographic",
            name="first_gen",
            field=models.BooleanField(
                blank=True,
                choices=[(None, ""), (True, "Yes"), (False, "No")],
                default=None,
                null=True,
                verbose_name="Are you a first-generation college student?",
            ),
        ),
    ]
