# Generated by Django 2.0.3 on 2018-08-25 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_fix_alumni_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolechange',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrolechange',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userstatuschange',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstatuschange',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
