# Generated by Django 2.0.3 on 2018-08-30 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_chapter_school_type'),
        ('users', '0013_auto_20180825_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlterChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='altered_member', to='chapters.Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altered_chapter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
