# Generated by Django 2.0.3 on 2018-08-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_useralterchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorgparticipate',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userorgparticipate',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userrolechange',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userrolechange',
            name='start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userstatuschange',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userstatuschange',
            name='start',
            field=models.DateField(),
        ),
    ]
