# Generated by Django 2.0.3 on 2018-09-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180831_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolechange',
            name='role',
            field=models.CharField(choices=[('adviser', 'Adviser'), ('board member', 'Board Member'), ('committee chair', 'Committee Chair'), ('corresponding secretary', 'Corresponding Secretary'), ('employer/ee', 'Employer/Ee'), ('faculty adviser', 'Faculty Adviser'), ('fundraising chair', 'Fundraising Chair'), ('house corporation president', 'House Corporation President'), ('house corporation treasurer', 'House Corporation Treasurer'), ('housing chair', 'Housing Chair'), ('national director', 'National Director'), ('national officer', 'National Officer'), ('other appointee', 'Other Appointee'), ('parent', 'Parent'), ('pd chair', 'Pd Chair'), ('pledge/new member educator', 'Pledge/New Member Educator'), ('president', 'President'), ('project chair', 'Project Chair'), ('recruitment chair', 'Recruitment Chair'), ('regent', 'Regent'), ('regional director', 'Regional Director'), ('risk management chair', 'Risk Management Chair'), ('rube goldberg chair', 'Rube Goldberg Chair'), ('rush chair', 'Rush Chair'), ('scholarship chair', 'Scholarship Chair'), ('scribe', 'Scribe'), ('secretary', 'Secretary'), ('service chair', 'Service Chair'), ('social/brotherhood chair', 'Social/Brotherhood Chair'), ('treasurer', 'Treasurer'), ('vice president', 'Vice President'), ('vice regent', 'Vice Regent'), ('website/social media chair', 'Website/Social Media Chair')], max_length=50),
        ),
    ]
