# Generated by Django 2.2.12 on 2021-11-14 17:56

from django.db import migrations, models


def remove_fakes(apps, schema_editor):
    User = apps.get_model("users", "User")
    fake_emails = User.objects.filter(email__icontains="fake")
    fake_emails.update(email="")
    fake_emails_school = User.objects.filter(email_school__icontains="fake")
    fake_emails_school.update(email_school="")


def undo_remove_fakes(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_auto_20210911_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_school",
            field=models.EmailField(
                blank=True,
                help_text="We will send an acknowledgement message. (ends in .edu)",
                max_length=254,
                verbose_name="School Email",
            ),
        ),
        migrations.RunPython(remove_fakes, undo_remove_fakes),
    ]
