# Generated by Django 2.2.12 on 2021-12-28 17:19
import datetime
from django.db import migrations, models
from core.models import forever, TODAY, TODAY_END


def set_deceased(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserStatusChange = apps.get_model("users", "UserStatusChange")
    deceased_users = User.objects.filter(deceased=True).all()
    print("Number of deceased", deceased_users.count())
    for user in deceased_users:
        deceased_date = user.deceased_date
        if deceased_date is None:
            deceased_date = datetime.date(year=2017, month=1, day=1)
            user.deceased_date = datetime.date(year=2017, month=1, day=1)
            user.save()
        ### Can not use custom functions b/c they don't exist
        # https://docs.djangoproject.com/en/4.0/topics/migrations/#historical-models
        current_status = user.status.filter(
            start__lte=TODAY_END, end__gte=TODAY_END
        ).all()
        for old_status in current_status:
            old_status.end = deceased_date - datetime.timedelta(days=1)
            old_status.save()
        UserStatusChange(
            user=user,
            created=TODAY,
            status="deceased",
            start=deceased_date,
            end=forever(),
        ).save()


def unset_deceased(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_auto_20211114_1056"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatuschange",
            name="status",
            field=models.CharField(
                choices=[
                    ("alumni", "alumni"),
                    ("alumnipend", "alumni pending"),
                    ("active", "active"),
                    ("activepend", "active pending"),
                    ("pnm", "prospective"),
                    ("away", "away"),
                    ("depledge", "depledge"),
                    ("advisor", "advisor"),
                    ("nonmember", "nonmember"),
                    ("resigned", "resigned"),
                    ("expelled", "expelled"),
                    ("friend", "friend"),
                    ("deceased", "deceased"),
                    ("suspended", "suspended"),
                    ("probation", "probation"),
                ],
                max_length=10,
            ),
        ),
        migrations.RunPython(set_deceased, unset_deceased),
    ]
