# Generated by Django 2.0.3 on 2018-09-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180903_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatuschange',
            name='status',
            field=models.CharField(choices=[('alumni', 'alumni'), ('active', 'active'), ('pnm', 'prospective'), ('away', 'away'), ('depledge', 'depledge')], max_length=10),
        ),
    ]
