# Generated by Django 2.0.3 on 2018-09-04 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180903_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolechange',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userstatuschange',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
