# Generated by Django 2.2.12 on 2022-08-07 22:36

import django.contrib.postgres.fields
from django.db import migrations, models
from core.models import TODAY_END


def unset_current_status_roles(apps, schema_editor):
    pass


def set_current_status_roles(apps, schema_editor):
    User = apps.get_model("users", "User")
    users = User.objects.all()
    total = users.count()
    print("Number of users", total)
    for count, user in enumerate(users):
        print(f"Working on user {count+1}/{total}")
        current_status = user.status.filter(
            start__lte=TODAY_END, end__gte=TODAY_END
        ).order_by("-start")
        if not current_status:
            # We will just take the last status user ever had
            current_status = user.status.order_by("-start")
        status = current_status.first()
        if not status:
            status = "alumni"
        else:
            status = status.status
        user.current_status = status
        current_roles = user.roles.filter(
            start__lte=TODAY_END, end__gte=TODAY_END
        ).values_list("role", flat=True)
        already_set_roles = user.current_roles
        set_roles = set()
        if already_set_roles:
            set_roles = set(already_set_roles)
        roles = set()
        if current_roles:
            roles = set(current_roles)
        new_roles = set_roles.union(roles)
        if new_roles:
            user.current_roles = list(new_roles)
        user.save(update_fields=["current_status", "current_roles"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_auto_20220216_2021"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_status",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.RunPython(set_current_status_roles, unset_current_status_roles),
    ]
