# Generated by Django 2.0.3 on 2018-09-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180903_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatuschange',
            name='status',
            field=models.CharField(choices=[('alumni', 'alumni'), ('alumnipend', 'alumni pending'), ('active', 'active'), ('activepend', 'active pending'), ('pnm', 'prospective'), ('away', 'away'), ('depledge', 'depledge')], max_length=10),
        ),
    ]
