# Generated by Django 3.2.15 on 2022-08-21 01:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_auto_20220807_1536"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="useralter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userdemographic",
            name="ability",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("sensory", "A sensory impairment (vision or hearing)"),
                    ("learning", "A learning disability (eg. ADHD, dyslexia)"),
                    (
                        "medical",
                        "A long-term medical illness (eg. epilepsy, cystic fibrosis)",
                    ),
                    ("mobility", "A mobility impairment"),
                    ("mental", "A mental health disorder"),
                    (
                        "temp",
                        "A temporary impairment due to illness or injury (eg. broken ankle, surgery)",
                    ),
                    (
                        "no_impairment",
                        "I do not identify with a disability or impairment",
                    ),
                    ("not_listed", "A disability or impairment not listed (write-in)"),
                    ("no_answer", "Prefer not to answer"),
                ],
                default="no_answer",
                max_length=500,
                null=True,
                verbose_name="How do you describe your disability / ability status? We are interested in this identification regardless of whether you typically request accommodations for this disability.",
            ),
        ),
        migrations.AlterField(
            model_name="userdemographic",
            name="gender",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("not_listed", "An identity not listed (write-in)"),
                    ("agender", "Agender"),
                    ("cisgender", "Cisgender"),
                    ("female", "Female"),
                    ("genderqueer", "Genderqueer/Gender non-conforming"),
                    ("intersex", "Intersex"),
                    ("male", "Male"),
                    ("nonbinary", "Nonbinary"),
                    ("no_answer", "Prefer not to answer"),
                    ("transgender", "Transgender"),
                ],
                default="no_answer",
                max_length=500,
                null=True,
                verbose_name="How would you describe your gender identity? (Select all that apply)",
            ),
        ),
        migrations.AlterField(
            model_name="userdemographic",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userdemographic",
            name="racial",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("asian", "Asian"),
                    ("black", "Black or African American"),
                    ("caucasian", "Caucasian / White"),
                    ("islander", "Native Hawaiian or Other Pacific Islander"),
                    ("middle_eastern", "Middle Eastern or North African"),
                    ("not_listed", "An identity not listed (write-in)"),
                    ("latinx/a/o", "Latinx/a/o or Hispanic"),
                    ("native", "Native American / First Nations"),
                    ("no_answer", "Prefer not to answer"),
                ],
                default="no_answer",
                max_length=500,
                null=True,
                verbose_name="With which racial and ethnic group(s) do you identify? (Select all that apply)",
            ),
        ),
        migrations.AlterField(
            model_name="userdemographic",
            name="sexual",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("asexual", "Asexual"),
                    ("bisexual", "Bisexual"),
                    ("not_listed", "An identity not listed (write-in)"),
                    ("heterosexual", "Heterosexual / straight"),
                    ("homosexual", "Homosexual / gay / lesbian"),
                    ("no_answer", "Prefer not to answer"),
                    ("queer", "Queer"),
                ],
                default="no_answer",
                max_length=500,
                null=True,
                verbose_name="How would you describe your sexual identity? (Select all that apply)",
            ),
        ),
        migrations.AlterField(
            model_name="userorgparticipate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userrolechange",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usersemestergpa",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="usersemesterservicehours",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="userstatuschange",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
