# Generated by Django 2.0.3 on 2018-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180905_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorgparticipate',
            name='end',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='userorgparticipate',
            name='start',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='userrolechange',
            name='end',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='userrolechange',
            name='start',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='userstatuschange',
            name='end',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='userstatuschange',
            name='start',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
