# Generated by Django 3.2.15 on 2022-09-12 01:26

from django.db import migrations, models

CHAPTER_OFFICER = {
    "corresponding secretary",
    "regent",
    "scribe",
    "treasurer",
    "vice regent",
}


def unset_officer(apps, schema_editor):
    pass


def set_officer(apps, schema_editor):
    User = apps.get_model("users", "User")
    users = User.objects.filter(current_roles__isnull=False)
    total = users.count()
    print("Number of users", total)
    for count, user in enumerate(users):
        print(f"Working on user {count + 1}/{total}")
        current_roles = set(user.current_roles) if user.current_roles else set()
        officer_roles = CHAPTER_OFFICER & current_roles
        if officer_roles:
            user.officer = True
            user.save(update_fields=["officer"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_auto_20220820_1812"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="officer",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_officer, unset_officer),
    ]
