# Generated by Django 3.2.15 on 2023-01-18 01:06

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_alter_userrolechange_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="graduation_year",
            field=models.PositiveIntegerField(
                default=core.models.current_year,
                help_text="Use the following format: YYYY",
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(
                        core.models.current_year_plus_10
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usersemestergpa",
            name="year",
            field=models.IntegerField(
                default=core.models.current_year,
                validators=[
                    django.core.validators.MinValueValidator(2016),
                    django.core.validators.MaxValueValidator(
                        core.models.current_year_plus_10
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="usersemesterservicehours",
            name="year",
            field=models.IntegerField(
                default=core.models.current_year,
                validators=[
                    django.core.validators.MinValueValidator(2016),
                    django.core.validators.MaxValueValidator(
                        core.models.current_year_plus_10
                    ),
                ],
            ),
        ),
    ]
