# Generated by Django 3.2.15 on 2023-05-27 14:36

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import email_signals.models


class Migration(migrations.Migration):

    dependencies = [
        ("viewflow", "0008_jsonfield_and_artifact"),
        ("address", "0003_auto_20200830_1851"),
        ("chapters", "0012_auto_20220820_1812"),
        ("users", "0026_auto_20230318_2320"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberUpdate",
            fields=[
                (
                    "process_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.process",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("matched", "A member was found to update information"),
                            ("created", "A member was created to update information"),
                            ("denied", "No member was found or created, update denied"),
                        ],
                        default="matched",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("approved", models.BooleanField(default=True)),
                ("badge_number", models.PositiveIntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("first_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("last_name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "maiden_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "preferred_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("nickname", models.CharField(blank=True, max_length=500, null=True)),
                ("suffix", models.CharField(blank=True, max_length=500, null=True)),
                ("email", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "email_school",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                ("degree", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "major_other",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("employer", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "employer_position",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "address",
                    address.models.AddressField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="update",
                        to="address.address",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_updates",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "employer_address",
                    address.models.AddressField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="update_employer",
                        to="address.address",
                    ),
                ),
                (
                    "major",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_updates",
                        to="chapters.chaptercurricula",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("viewflow.process", email_signals.models.EmailSignalMixin),
        ),
    ]
