# Generated by Django 2.2.3 on 2019-08-10 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0011_auto_20190222_0946'),
        ('users', '0026_auto_20190217_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('scribe', 'Scribe'), ('regent', 'Regent'), ('treasurer', 'Treasurer'), ('vice regent', 'Vice Regent'), ('corresponding secretary', 'Corresponding Secretary')], max_length=50, null=True)),
                ('chapter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='altered_member', to='chapters.Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='altered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAlterChapter',
        ),
    ]
