# Generated by Django 3.2.15 on 2023-09-20 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_memberupdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="user_id",
            field=models.CharField(max_length=20, default="NOT SET", unique=False),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                max_length=20, blank=True, null=True, default="Trash", unique=False
            ),
            preserve_default=True,
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
    ]
