# Generated by Django 2.2.3 on 2019-08-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190812_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralter',
            name='role',
            field=models.CharField(choices=[('corresponding secretary', 'Corresponding Secretary'), ('regent', 'Regent'), ('scribe', 'Scribe'), ('treasurer', 'Treasurer'), ('vice regent', 'Vice Regent'), (None, '------------')], max_length=50, null=True),
        ),
    ]
