# Generated by Django 3.2.15 on 2023-10-14 05:39

from django.db import migrations, models


def unset_cc_status(apps, schema_editor):
    UserStatusChange = apps.get_model("users", "UserStatusChange")
    users_statuses = UserStatusChange.objects.filter(
        user__chapter__candidate_chapter=True, status__in=["activeCC", "alumniCC"]
    )
    total = users_statuses.count()
    print("Number of users_statuses", total)
    for count, users_status in enumerate(users_statuses):
        print(f"Working on users_status {count + 1}/{total}")
        status = users_status.status
        new_status = {"activeCC": "active", "alumniCC": "alumni"}.get(status, status)
        users_status.status = new_status
    UserStatusChange.objects.bulk_update(users_statuses, ["status"])


def set_cc_status(apps, schema_editor):
    UserStatusChange = apps.get_model("users", "UserStatusChange")
    users_statuses = UserStatusChange.objects.filter(
        user__chapter__candidate_chapter=True, status__in=["active", "alumni"]
    )
    total = users_statuses.count()
    print("Number of users_statuses", total)
    for count, users_status in enumerate(users_statuses):
        print(f"Working on users_status {count + 1}/{total}")
        status = users_status.status
        new_status = {"active": "activeCC", "alumni": "alumniCC"}.get(status, status)
        users_status.status = new_status
    UserStatusChange.objects.bulk_update(users_statuses, ["status"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_auto_20230919_2106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatuschange",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("activeCC", "Active"),
                    ("activepend", "Active Pending"),
                    ("advisor", "Advisor"),
                    ("alumni", "Alumni"),
                    ("alumniCC", "Alumni"),
                    ("alumnipend", "Alumni Pending"),
                    ("away", "Away"),
                    ("deceased", "Deceased"),
                    ("depledge", "Depledge"),
                    ("expelled", "Expelled"),
                    ("friend", "Friend"),
                    ("nonmember", "Nonmember"),
                    ("pendexpul", "Pending Expulsion"),
                    ("probation", "Probation"),
                    ("pnm", "Prospective"),
                    ("resigned", "Resigned"),
                    ("resignedCC", "Resigned"),
                    ("suspended", "Suspended"),
                ],
                max_length=10,
            ),
        ),
        migrations.RunPython(set_cc_status, unset_cc_status),
    ]
