# Generated by Django 3.2.15 on 2023-10-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_alter_userstatuschange_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="preferred_pronouns",
            field=models.CharField(
                blank=True,
                help_text="Pronouns are the part of speech used to refer to someone in the third person. We want to know how to respectfully refer to you.",
                max_length=255,
                null=True,
                verbose_name="Preferred Pronouns",
            ),
        ),
        migrations.AddField(
            model_name="memberupdate",
            name="preferred_pronouns",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_pronouns",
            field=models.CharField(
                blank=True,
                help_text="Pronouns are the part of speech used to refer to someone in the third person. We want to know how to respectfully refer to you.",
                max_length=255,
                null=True,
                verbose_name="Preferred Pronouns",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="Preferred First Name - eg my first name is Kevin but I go by my middle name Henry.",
                max_length=255,
                null=True,
                verbose_name="Preferred Name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="preferred_name",
            field=models.CharField(
                blank=True,
                help_text="Preferred First Name - eg my first name is Kevin but I go by my middle name Henry.",
                max_length=255,
                null=True,
                verbose_name="Preferred Name",
            ),
        ),
    ]
