# Generated by Django 2.2.3 on 2019-12-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatuschange',
            name='status',
            field=models.CharField(choices=[('alumni', 'alumni'), ('alumnipend', 'alumni pending'), ('active', 'active'), ('activepend', 'active pending'), ('pnm', 'prospective'), ('away', 'away'), ('depledge', 'depledge'), ('advisor', 'advisor')], max_length=10),
        ),
    ]
