# Generated by Django 3.2.15 on 2024-04-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_auto_20231231_2219"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="unsubscribe_email",
            field=models.BooleanField(
                default=False,
                help_text="Select if you no longer wish to receive email from Theta Tau",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="unsubscribe_paper_gear",
            field=models.BooleanField(
                default=False,
                help_text="Select if you no longer wish to receive paper copies of the GEAR",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unsubscribe_email",
            field=models.BooleanField(
                default=False,
                help_text="Select if you no longer wish to receive email from Theta Tau",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unsubscribe_paper_gear",
            field=models.BooleanField(
                default=False,
                help_text="Select if you no longer wish to receive paper copies of the GEAR",
            ),
        ),
    ]
