# Generated by Django 4.2.23 on 2026-07-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_auto_20250217_1654"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="class_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("freshman", "Freshman/1st Year"),
                    ("sophomore", "Sophomore/2nd Year"),
                    ("junior", "Junior/3rd Year"),
                    ("senior", "Senior/4th Year"),
                    ("senior_plus", "Senior +/5th Year or more"),
                    ("graduate_student", "Graduate Student"),
                    ("none", ""),
                ],
                max_length=50,
                verbose_name="Class Year",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="class_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("freshman", "Freshman/1st Year"),
                    ("sophomore", "Sophomore/2nd Year"),
                    ("junior", "Junior/3rd Year"),
                    ("senior", "Senior/4th Year"),
                    ("senior_plus", "Senior +/5th Year or more"),
                    ("graduate_student", "Graduate Student"),
                    ("none", ""),
                ],
                max_length=50,
                verbose_name="Class Year",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Admin-only tags for record-keeping (e.g. trustee at a chapter, non-regional national director). Not shown on member profiles.",
                related_name="users",
                to="users.usertag",
            ),
        ),
    ]
