# Generated by Django 4.2.23 on 2026-07-07 02:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_usertag_alter_historicaluser_class_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="unsubscribe_categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                help_text="Per-mailing opt-outs (e.g. birthday, velocitas). See users.unsubscribe.UNSUBSCRIBE_CATEGORIES for valid slugs.",
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unsubscribe_categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                help_text="Per-mailing opt-outs (e.g. birthday, velocitas). See users.unsubscribe.UNSUBSCRIBE_CATEGORIES for valid slugs.",
                size=None,
            ),
        ),
    ]
