# Generated by Django 4.2.23 on 2026-07-27 05:02, then edited to populate the
# new Organization FK from the existing free-text `UserOrgParticipate.org_name`,
# condensing case / whitespace / punctuation variants onto a single row. The
# original `org_name` column is intentionally kept for now (dropped in a later
# migration once every reader uses the FK). More aggressive fuzzy de-duplication
# is available on demand via the `merge_duplicate_organizations` command.

import re

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def _clean(name):
    """Whitespace-normalize but preserve casing for display."""
    s = (name or "").strip()
    s = re.sub(r"\s+", " ", s)
    return s.rstrip(" .,;:")


def _key(name):
    """Case-folded dedup key: collapses whitespace and strips punctuation."""
    s = _clean(name).casefold()
    s = re.sub(r"[^\w\s]", "", s)
    s = re.sub(r"\s+", " ", s).strip()
    return s


def populate_organization_fk(apps, schema_editor):
    Organization = apps.get_model("users", "Organization")
    UserOrgParticipate = apps.get_model("users", "UserOrgParticipate")
    key_to_org = {}
    qs = UserOrgParticipate.objects.exclude(org_name="").exclude(org_name__isnull=True)
    for participation in qs.iterator():
        cleaned = _clean(participation.org_name)
        key = _key(cleaned)
        if not key:
            continue
        org = key_to_org.get(key)
        if org is None:
            # Prefer an existing case-insensitive match, else create with the
            # cleaned original casing (a better display than a lowercase key).
            org = Organization.objects.filter(name__iexact=cleaned).first()
            if org is None:
                org, _ = Organization.objects.get_or_create(name=cleaned)
            key_to_org[key] = org
        participation.organization = org
        participation.save(update_fields=["organization"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_useralter_hide_natoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="userorgparticipate",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="participations",
                to="users.organization",
            ),
        ),
        migrations.RunPython(populate_organization_fk, reverse_code=migrations.RunPython.noop),
    ]
