# Generated by Django 4.2.23 on 2026-08-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdemographic",
            name="international",
            field=models.BooleanField(
                blank=True,
                choices=[(None, ""), (True, "Yes"), (False, "No")],
                default=None,
                null=True,
                verbose_name="Are you considered an international student by your college/university?",
            ),
        ),
    ]
