# Generated by Django 4.2.23 on 2026-08-06 22:14

from django.db import migrations, models

VISIBILITY_FIELDS = ("email_visibility", "phone_visibility", "address_visibility")


def officers_to_no_one(apps, schema_editor):
    """Fold the retired "My chapter's officers only" level into "no_one".

    Chapter officers can now always see their own chapter's members, so the two
    levels mean the same thing and only one is offered.
    """
    for model_name in ("User", "HistoricalUser"):
        model = apps.get_model("users", model_name)
        for field in VISIBILITY_FIELDS:
            model.objects.filter(**{field: "officers"}).update(**{field: "no_one"})


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_userdemographic_international"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="address_visibility",
            field=models.CharField(
                choices=[
                    ("no_one", "Only National Officers, Admins, and my chapter's officers"),
                    ("chapter", "Members of my chapter"),
                    ("members", "Any member on the site"),
                ],
                default="no_one",
                help_text="Who may see your mailing address on your member profile and in member lists. Your chapter's officers, National Officers, and Admins can always see it.",
                max_length=10,
                verbose_name="Address visibility",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="email_visibility",
            field=models.CharField(
                choices=[
                    ("no_one", "Only National Officers, Admins, and my chapter's officers"),
                    ("chapter", "Members of my chapter"),
                    ("members", "Any member on the site"),
                ],
                default="no_one",
                help_text="Who may see your email addresses on your member profile and in member lists. Your chapter's officers, National Officers, and Admins can always see them.",
                max_length=10,
                verbose_name="Email visibility",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="phone_visibility",
            field=models.CharField(
                choices=[
                    ("no_one", "Only National Officers, Admins, and my chapter's officers"),
                    ("chapter", "Members of my chapter"),
                    ("members", "Any member on the site"),
                ],
                default="no_one",
                help_text="Who may see your phone number on your member profile and in member lists. Your chapter's officers, National Officers, and Admins can always see it.",
                max_length=10,
                verbose_name="Phone visibility",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="address_visibility",
            field=models.CharField(
                choices=[
                    ("no_one", "Only National Officers, Admins, and my chapter's officers"),
                    ("chapter", "Members of my chapter"),
                    ("members", "Any member on the site"),
                ],
                default="no_one",
                help_text="Who may see your mailing address on your member profile and in member lists. Your chapter's officers, National Officers, and Admins can always see it.",
                max_length=10,
                verbose_name="Address visibility",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_visibility",
            field=models.CharField(
                choices=[
                    ("no_one", "Only National Officers, Admins, and my chapter's officers"),
                    ("chapter", "Members of my chapter"),
                    ("members", "Any member on the site"),
                ],
                default="no_one",
                help_text="Who may see your email addresses on your member profile and in member lists. Your chapter's officers, National Officers, and Admins can always see them.",
                max_length=10,
                verbose_name="Email visibility",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_visibility",
            field=models.CharField(
                choices=[
                    ("no_one", "Only National Officers, Admins, and my chapter's officers"),
                    ("chapter", "Members of my chapter"),
                    ("members", "Any member on the site"),
                ],
                default="no_one",
                help_text="Who may see your phone number on your member profile and in member lists. Your chapter's officers, National Officers, and Admins can always see it.",
                max_length=10,
                verbose_name="Phone visibility",
            ),
        ),
        migrations.RunPython(officers_to_no_one, migrations.RunPython.noop),
    ]
