# Generated by Django 4.2.23 on 2026-08-10, then rewritten to preserve the
# existing text in `user.employer` / `user.employer_position`. Django's
# auto-generated AlterField would have tried to cast the text straight to a
# foreign key, so this follows the same rename -> add FK -> populate -> drop
# pattern as `forms/0044_employer.py`.

import re

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


# Trailing legal / entity suffixes that should not by themselves make two
# employer names look distinct (e.g. "Boeing" vs "Boeing, Inc.").
_SUFFIX_RE = re.compile(
    r",?\s*(inc|incorporated|llc|l\.l\.c\.|corp|corporation|co|company|" r"ltd|limited|plc|llp|lp|gmbh)\.?$",
    re.IGNORECASE,
)


def _clean(name):
    """Whitespace-normalize but preserve casing for display."""
    s = (name or "").strip()
    s = re.sub(r"\s+", " ", s)
    return s.rstrip(" .,;:")


def _key(name):
    """Case-folded dedup key: collapses whitespace, strips punctuation and
    common company suffixes."""
    s = _clean(name).casefold()
    s = _SUFFIX_RE.sub("", s)
    return re.sub(r"\s+", " ", s).strip(" .,;:")


def populate_employer(apps, schema_editor):
    Employer = apps.get_model("forms", "Employer")
    User = apps.get_model("users", "User")
    HistoricalUser = apps.get_model("users", "HistoricalUser")
    key_to_employer = {}

    def resolve(raw):
        cleaned = _clean(raw)[:200]
        key = _key(cleaned)
        if not key:
            return None
        employer = key_to_employer.get(key)
        if employer is None:
            # Prefer an existing case-insensitive match (the same employer may
            # already be on a status change), else create it with the cleaned
            # original casing.
            employer = Employer.objects.filter(name__iexact=cleaned).first()
            if employer is None:
                employer, _ = Employer.objects.get_or_create(name=cleaned)
            key_to_employer[key] = employer
        return employer

    for model in (User, HistoricalUser):
        names = (
            model.objects.exclude(employer_old="")
            .exclude(employer_old__isnull=True)
            .values_list("employer_old", flat=True)
            .distinct()
        )
        for raw in names:
            employer = resolve(raw)
            if employer is not None:
                model.objects.filter(employer_old=raw).update(employer=employer)


def populate_positions(apps, schema_editor):
    Position = apps.get_model("users", "Position")
    User = apps.get_model("users", "User")
    cache = {}
    qs = User.objects.exclude(employer_position="").exclude(employer_position__isnull=True)
    for user in qs.iterator():
        positions = []
        for raw in user.employer_position.split(","):
            name = " ".join(raw.split())[:200]
            if not name:
                continue
            position = cache.get(name.casefold())
            if position is None:
                position = Position.objects.filter(name__iexact=name).first()
                if position is None:
                    position = Position.objects.create(name=name)
                cache[name.casefold()] = position
            positions.append(position)
        if positions:
            user.employer_positions.set(positions)


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0044_employer"),
        ("users", "0043_useralter_hide_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "ordering": ["name"],
            },
        ),
        migrations.RenameField(
            model_name="user",
            old_name="employer",
            new_name="employer_old",
        ),
        migrations.RenameField(
            model_name="historicaluser",
            old_name="employer",
            new_name="employer_old",
        ),
        migrations.AddField(
            model_name="user",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="forms.employer",
            ),
        ),
        migrations.AddField(
            model_name="historicaluser",
            name="employer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="forms.employer",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="employer_positions",
            field=models.ManyToManyField(
                blank=True,
                related_name="members",
                to="users.position",
                verbose_name="Position / Job Title",
            ),
        ),
        migrations.RunPython(populate_employer, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(populate_positions, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="employer_old",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="employer_old",
        ),
        migrations.RemoveField(
            model_name="user",
            name="employer_position",
        ),
        migrations.RemoveField(
            model_name="historicaluser",
            name="employer_position",
        ),
        migrations.AlterField(
            model_name="user",
            name="employer_changed",
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor="employer_id"),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="employer_changed",
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor="employer_id"),
        ),
    ]
