# Generated by Django 2.2.12 on 2021-05-29 20:37

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import notes.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chapters", "0006_auto_20210424_1306"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("note", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=notes.models.get_upload_path
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("responsible", "Responsible"),
                            ("not_responsible", "Not Responsible"),
                            ("accolade", "Accolade"),
                            ("note", "Note"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                (
                    "restricted",
                    models.BooleanField(
                        default=False,
                        help_text="If True only EC will be able to read or edit",
                        verbose_name="Restrict read/write to Executive Council",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_modified_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-modified"], "abstract": False,},
        ),
        migrations.CreateModel(
            name="ChapterNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("note", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to=notes.models.get_upload_path
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("responsible", "Responsible"),
                            ("not_responsible", "Not Responsible"),
                            ("accolade", "Accolade"),
                            ("note", "Note"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                (
                    "restricted",
                    models.BooleanField(
                        default=False,
                        help_text="If True only EC will be able to read or edit",
                        verbose_name="Restrict read/write to Executive Council",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="chapters.Chapter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_created_chapter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes_modified_chapter",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-modified"], "abstract": False,},
        ),
    ]
