# Generated by Django 3.2.15 on 2023-08-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_auto_20220820_1812"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapternote",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subnotes",
                to="notes.chapternote",
            ),
        ),
        migrations.AddField(
            model_name="usernote",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subnotes",
                to="notes.usernote",
            ),
        ),
    ]
