# Generated by Django 2.2.12 on 2022-05-15 21:32

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255)),
                ("value", ckeditor.fields.RichTextField()),
                ("description", models.TextField()),
            ],
            options={
                "ordering": ["-modified"],
            },
        ),
    ]
