# Generated by Django 2.0.3 on 2018-06-14 18:28
import warnings
import httplib2
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage
import submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        ('scores', '0001_initial'),
    ]
    try:
        storage = gdstorage.storage.GoogleDriveStorage()
    except httplib2.ServerNotFoundError:
        storage = None
        warnings.warn("Unable to connect to Google drive!")
    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(storage=storage, upload_to=submissions.models.get_upload_path)),
                ('name', models.CharField(max_length=50)),
                ('score', models.FloatField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='chapters.Chapter')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='scores.ScoreType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
