# Generated by Django 2.2.12 on 2020-05-17 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scores", "0001_initial"),
        ("chapters", "0002_chapter_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Submission Date",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=submissions.models.get_upload_path),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Submission Name"),
                ),
                ("slug", models.SlugField()),
                ("score", models.FloatField(default=0)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="chapters.Chapter",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submissions",
                        to="scores.ScoreType",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
