# Generated by Django 2.0.3 on 2018-07-06 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
