# Generated by Django 2.2.12 on 2022-01-03 22:53

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import submissions.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submissions", "0002_submission_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="GearArticle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("article", ckeditor.fields.RichTextField()),
                ("reviewed", models.BooleanField(blank=True, default=False, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        null=True,
                        related_name="gear_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gear",
                        to="submissions.Submission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        upload_to=submissions.models.get_picture_upload_path
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="submissions.GearArticle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
