# Generated by Django 2.2.12 on 2022-01-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0004_auto_20220116_1913"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="slug",
            field=models.SlugField(max_length=200),
        ),
    ]
