# Generated by Django 2.0.3 on 2018-09-08 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20180903_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Submission Date'),
        ),
    ]
