# Generated by Django 2.0.3 on 2018-09-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_auto_20180908_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Submission Name'),
        ),
    ]
