# Generated by Django 2.2.12 on 2022-07-04 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_auto_20220117_0926"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geararticle",
            name="authors",
            field=models.ManyToManyField(
                related_name="gear_articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
