# Generated by Django 3.2.15 on 2024-01-01 05:19

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("submissions", "0007_auto_20220820_1812"),
    ]

    operations = [
        migrations.AddField(
            model_name="geararticle",
            name="created_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gear_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="The user that created this object",
            ),
        ),
        migrations.AddField(
            model_name="geararticle",
            name="modified_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gear_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="The user that created this object",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="created_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="The user that created this object",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="modified_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="The user that created this object",
            ),
        ),
    ]
