# Generated by Django 4.2.23 on 2026-07-17 01:09

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields
import thetatauCMT.awards.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AwardType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional grouping label for the award (admin-managed).",
                        max_length=255,
                        verbose_name="Category",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("chapter", "Chapter"),
                            ("region", "Region"),
                            ("alumni", "Alumni"),
                            ("active", "Active"),
                            ("pnm", "PNM"),
                            ("national", "National"),
                        ],
                        help_text="Determines the recipient kind and eligibility scope.",
                        max_length=20,
                        verbose_name="Level",
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True,
                        help_text="Badge or icon shown on profiles and inline next to names.",
                        null=True,
                        upload_to=thetatauCMT.awards.models.get_badge_image_path,
                        verbose_name="Badge / icon",
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        blank=True,
                        help_text="Optional weight for standings / rollups.",
                        null=True,
                        verbose_name="Points",
                    ),
                ),
                (
                    "grant_method",
                    models.CharField(
                        choices=[("direct", "Direct grant"), ("nomination_workflow", "Nomination workflow")],
                        default="direct",
                        help_text="How the award is granted: directly or via a nomination workflow.",
                        max_length=20,
                        verbose_name="Grant method",
                    ),
                ),
                (
                    "recurrence",
                    models.CharField(
                        choices=[("one_time", "One-time"), ("recurring", "Recurring")],
                        default="one_time",
                        help_text="Whether the award recurs each cycle or is granted only once.",
                        max_length=20,
                        verbose_name="Recurrence",
                    ),
                ),
                (
                    "single_winner",
                    models.BooleanField(
                        default=False,
                        help_text="Enforce exactly one winner per cycle when set.",
                        verbose_name="Single winner per cycle",
                    ),
                ),
                (
                    "allow_multiple_winners",
                    models.BooleanField(
                        default=False,
                        help_text="Allow more than one winner per cycle.",
                        verbose_name="Allow multiple winners",
                    ),
                ),
                (
                    "allow_multiple_nominations",
                    models.BooleanField(
                        default=False,
                        help_text="Allow the same recipient to be nominated multiple times per cycle.",
                        verbose_name="Allow multiple nominations",
                    ),
                ),
                (
                    "nominator_scope",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[("member", "Member"), ("officer", "Officer"), ("national", "National")],
                        help_text="Which roles may nominate for this award; drives the per-role nomination lists.",
                        max_length=50,
                        verbose_name="Nominator scope",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Retired awards are excluded from active lists.", verbose_name="Active"
                    ),
                ),
            ],
            options={
                "verbose_name": "Award Type",
                "verbose_name_plural": "Award Types",
                "ordering": ["name"],
            },
        ),
    ]
