# Generated by Django 4.2.23 on 2026-07-17 01:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_event_options_alter_event_managers_and_more"),
        ("awards", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardCycle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Label for the cycle, e.g. "2025", "Fall 2025", "2025 Convention".',
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[("year", "Year"), ("term", "Term"), ("event", "Event")],
                        default="year",
                        max_length=10,
                        verbose_name="Period type",
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="Start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank for an open / ongoing cycle.",
                        null=True,
                        verbose_name="End date",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to an event, for event-based cycles.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_cycles",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Award Cycle",
                "verbose_name_plural": "Award Cycles",
                "ordering": ["-start_date", "name"],
            },
        ),
    ]
