# Generated by Django 4.2.23 on 2026-07-17 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import thetatauCMT.awards.models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0015_add_address_socials_to_chapter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regions", "0006_alter_region_id"),
        ("awards", "0002_awardcycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardGrant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "granted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Real system timestamp when the grant was recorded.",
                        verbose_name="Granted at",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        default=thetatauCMT.awards.models.default_effective_date,
                        help_text="Date the award takes effect; may be backdated for historical records.",
                        verbose_name="Effective date",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked")],
                        db_index=True,
                        default="active",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("direct", "Direct"), ("nomination", "Nomination"), ("import", "Import")],
                        default="direct",
                        max_length=12,
                        verbose_name="Source",
                    ),
                ),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoke_reason", models.TextField(blank=True)),
                (
                    "award_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="grants", to="awards.awardtype"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="grants", to="awards.awardcycle"
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="award_grants_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="award_grants",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "recipient_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="award_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="award_grants",
                        to="regions.region",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_grants_revoked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Award Grant",
                "verbose_name_plural": "Award Grants",
                "ordering": ["-effective_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GrantAudit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("revoked", "Revoked"),
                            ("imported", "Imported"),
                            ("updated", "Updated"),
                        ],
                        max_length=12,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_grant_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_entries",
                        to="awards.awardgrant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Grant Audit",
                "verbose_name_plural": "Grant Audit Entries",
                "ordering": ["timestamp", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="awardgrant",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("recipient_member__isnull", False),
                        ("recipient_chapter__isnull", True),
                        ("recipient_region__isnull", True),
                    ),
                    models.Q(
                        ("recipient_member__isnull", True),
                        ("recipient_chapter__isnull", False),
                        ("recipient_region__isnull", True),
                    ),
                    models.Q(
                        ("recipient_member__isnull", True),
                        ("recipient_chapter__isnull", True),
                        ("recipient_region__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="awards_grant_exactly_one_recipient",
            ),
        ),
    ]
