# Generated by Django 4.2.23 on 2026-07-17 02:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0015_add_address_socials_to_chapter"),
        ("regions", "0006_alter_region_id"),
        ("awards", "0003_awardgrant_grantaudit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EligibilityRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("member_status", "Member status"),
                            ("chapter_scope", "Chapter scope"),
                            ("region_scope", "Region scope"),
                            ("recipient_kind", "Recipient kind"),
                            ("custom_hook", "Custom hook"),
                        ],
                        max_length=20,
                        verbose_name="Rule type",
                    ),
                ),
                (
                    "member_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("alumni", "Alumni"), ("pnm", "PNM")],
                        help_text="For member-status rules: which member status is eligible.",
                        max_length=10,
                        verbose_name="Member status",
                    ),
                ),
                (
                    "hook_key",
                    models.CharField(
                        blank=True,
                        help_text="For custom-hook rules: the registered key of the pluggable check.",
                        max_length=100,
                        verbose_name="Hook key",
                    ),
                ),
                (
                    "params",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parameters for the custom hook (or the recipient-kind guard).",
                        verbose_name="Parameters",
                    ),
                ),
                (
                    "award_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_rules",
                        to="awards.awardtype",
                    ),
                ),
                (
                    "chapters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="For chapter-scope rules: the chapters recipients must belong to.",
                        related_name="award_eligibility_rules",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="For region-scope rules: the regions recipients must belong to.",
                        related_name="award_eligibility_rules",
                        to="regions.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eligibility Rule",
                "verbose_name_plural": "Eligibility Rules",
            },
        ),
    ]
