# Generated by Django 4.2.23 on 2026-07-17 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import thetatauCMT.awards.models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0015_add_address_socials_to_chapter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("viewflow", "0008_jsonfield_and_artifact"),
        ("regions", "0006_alter_region_id"),
        ("awards", "0004_eligibilityrule"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardNominationProcess",
            fields=[
                (
                    "process_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.process",
                    ),
                ),
                ("justification", models.TextField(blank=True, verbose_name="Justification")),
                (
                    "supporting_docs",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=thetatauCMT.awards.models.get_nomination_docs_path,
                        verbose_name="Supporting documents",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=10,
                        verbose_name="Result",
                    ),
                ),
                ("reject_reason", models.TextField(blank=True, verbose_name="Reject reason")),
                (
                    "award_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="nominations", to="awards.awardtype"
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="nominations", to="awards.awardcycle"
                    ),
                ),
                (
                    "nominator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="award_nominations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="award_nominations",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "recipient_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="award_nominations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="award_nominations",
                        to="regions.region",
                    ),
                ),
                (
                    "resulting_grant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_nomination",
                        to="awards.awardgrant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Award Nomination",
                "verbose_name_plural": "Award Nominations",
            },
            bases=("viewflow.process",),
        ),
    ]
