# Generated by Django 4.2.23 on 2026-07-17 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("awards", "0005_awardnominationprocess"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardnominationprocess",
            name="review_notes",
            field=models.TextField(blank=True, verbose_name="Review notes"),
        ),
        migrations.AddField(
            model_name="awardnominationprocess",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="awardnominationprocess",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="award_nominations_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
