# Generated by Django 4.2.23 on 2026-07-17 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import thetatauCMT.awards.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("awards", "0006_awardnominationprocess_review_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardtype",
            name="auto_generate_certificate",
            field=models.BooleanField(
                default=False,
                help_text="Automatically generate a certificate / letter when this award is granted.",
                verbose_name="Auto-generate certificate",
            ),
        ),
        migrations.CreateModel(
            name="GrantArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "artifact_type",
                    models.CharField(choices=[("generated", "Generated"), ("uploaded", "Uploaded")], max_length=10),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=thetatauCMT.awards.models.get_certificate_path, verbose_name="Certificate / letter"
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_artifacts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="awards.awardgrant"
                    ),
                ),
            ],
            options={
                "verbose_name": "Grant Artifact",
                "verbose_name_plural": "Grant Artifacts",
                "ordering": ["-id"],
            },
        ),
    ]
