# Generated by Django 4.2.23 on 2026-07-17 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("awards", "0007_awardtype_auto_generate_certificate_grantartifact"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardDigestRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("grant_count", models.IntegerField(default=0)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_digests_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Award Digest Run",
                "verbose_name_plural": "Award Digest Runs",
                "ordering": ["-period_start"],
            },
        ),
        migrations.AddConstraint(
            model_name="awarddigestrun",
            constraint=models.UniqueConstraint(
                fields=("period_start", "period_end"), name="awards_digest_unique_period"
            ),
        ),
    ]
