# Generated by Django 4.2.23 on 2026-07-17 04:24

from django.db import migrations, models
import django.utils.timezone
import thetatauCMT.awards.models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0008_awarddigestrun_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficerBadge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("alumni programs director", "Alumni Programs Director"),
                            ("candidate chapter director", "Candidate Chapter Director"),
                            ("council delegate", "Council Delegate"),
                            ("educational foundation board of director", "Educational Foundation Board Of Director"),
                            ("expansion director", "Expansion Director"),
                            ("grand inner guard", "Grand Inner Guard"),
                            ("grand marshal", "Grand Marshal"),
                            ("grand outer guard", "Grand Outer Guard"),
                            ("grand regent", "Grand Regent"),
                            ("grand scribe", "Grand Scribe"),
                            ("grand treasurer", "Grand Treasurer"),
                            ("grand vice regent", "Grand Vice Regent"),
                            ("national director", "National Director"),
                            ("national officer", "National Officer"),
                            ("national operations manager", "National Operations Manager"),
                            ("professional development director", "Professional Development Director"),
                            ("regional director", "Regional Director"),
                            ("service director", "Service Director"),
                        ],
                        max_length=100,
                        unique=True,
                        verbose_name="Role",
                    ),
                ),
                (
                    "badge_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=thetatauCMT.awards.models.get_officer_badge_path,
                        verbose_name="Badge image",
                    ),
                ),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        help_text="Optional CSS / FontAwesome class used when no image is set.",
                        max_length=100,
                        verbose_name="Icon class",
                    ),
                ),
                (
                    "short_label",
                    models.CharField(
                        blank=True,
                        help_text="Tooltip / alt text; defaults to the role name.",
                        max_length=50,
                        verbose_name="Short label",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Officer Badge",
                "verbose_name_plural": "Officer Badges",
                "ordering": ["role"],
            },
        ),
    ]
