# Generated by Django 4.2.23 on 2026-07-17 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regions", "0006_alter_region_id"),
        ("chapters", "0015_add_address_socials_to_chapter"),
        ("awards", "0009_officerbadge"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwardImportMatchQueueItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "upload_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, help_text="Groups all rows that arrived in the same import."
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True,
                        help_text="Stable hash of the raw identity fields; keeps re-imports idempotent.",
                        max_length=64,
                    ),
                ),
                (
                    "recipient_kind",
                    models.CharField(
                        choices=[("member", "Member"), ("chapter", "Chapter"), ("region", "Region")], max_length=10
                    ),
                ),
                (
                    "raw_row",
                    models.JSONField(
                        blank=True, default=dict, help_text="The full original import row, preserved for audit."
                    ),
                ),
                ("raw_award", models.CharField(blank=True, default="", max_length=255)),
                ("raw_recipient", models.CharField(blank=True, default="", max_length=255)),
                ("raw_cycle", models.CharField(blank=True, default="", max_length=255)),
                ("raw_effective_date", models.CharField(blank=True, default="", max_length=32)),
                ("effective_date", models.DateField(blank=True, null=True)),
                ("candidate_matches", models.JSONField(blank=True, default=list)),
                ("best_score", models.FloatField(default=0.0)),
                ("import_error", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending Review"), ("resolved", "Resolved"), ("skipped", "Skipped")],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "award_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_queue_items",
                        to="awards.awardtype",
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_queue_items",
                        to="awards.awardcycle",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_imports_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_grant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_queue_items",
                        to="awards.awardgrant",
                    ),
                ),
                (
                    "resolved_recipient_chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_import_resolutions",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "resolved_recipient_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_import_resolutions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_recipient_region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_import_resolutions",
                        to="regions.region",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="award_imports_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Award Import Match Queue Item",
                "verbose_name_plural": "Award Import Match Queue Items",
                "ordering": ["-created"],
                "indexes": [models.Index(fields=["status", "fingerprint"], name="awards_awar_status_292a33_idx")],
            },
        ),
    ]
