# Generated by Django 4.2.23 on 2026-07-17 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_event_options_alter_event_managers_and_more"),
        ("awards", "0010_awardimportmatchqueueitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="awardcycle",
            options={
                "ordering": ["-start_date", "name"],
                "verbose_name": "Award Period",
                "verbose_name_plural": "Award Periods",
            },
        ),
        migrations.AlterField(
            model_name="awardcycle",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Leave blank for an open / ongoing award period.",
                null=True,
                verbose_name="End date",
            ),
        ),
        migrations.AlterField(
            model_name="awardcycle",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to an event, for event-based award periods.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="award_cycles",
                to="events.event",
            ),
        ),
        migrations.AlterField(
            model_name="awardcycle",
            name="name",
            field=models.CharField(
                help_text='Label for the award period, e.g. "2025", "Fall 2025", "2025 Convention".',
                max_length=255,
                verbose_name="Name",
            ),
        ),
    ]
