# Generated by Django 4.2.23 on 2026-08-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("awards", "0011_alter_awardcycle_options_alter_awardcycle_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="awardtype",
            name="eligibility",
            field=models.TextField(
                blank=True,
                help_text="Who may receive this award, in plain language, shown on the award catalog and the nomination form. The configured eligibility rules are listed alongside it.",
                verbose_name="Eligibility",
            ),
        ),
    ]
