# Generated by Django 2.2.28 on 2022-08-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainings", "0002_alter_training_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="course_title",
            field=models.CharField(max_length=500),
        ),
    ]
