# Generated by Django 4.2.23 on 2026-08-01 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guides", "0002_tourstep_usertourcompletion"),
        ("announcements", "0002_alter_announcement_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="audience",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("member", "Member"),
                    ("officer", "Officer"),
                    ("natoff", "National Officer"),
                ],
                default="member",
                help_text="Minimum audience needed to see this announcement. 'Member' is every signed-in user.",
                max_length=20,
                verbose_name="Audience",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="dismissible",
            field=models.BooleanField(
                default=True,
                help_text="Uncheck for a compliance notice that must stay pinned until it expires.",
                verbose_name="Dismissible",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="feature",
            field=models.ForeignKey(
                blank=True,
                help_text="The catalog entry this announcement is about, if any. Enables the 'Show me' link.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="announcements",
                to="guides.feature",
                verbose_name="Feature",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="roles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Show only to holders of these duty roles, e.g. ['treasurer']. Empty shows it to everyone.",
                verbose_name="Roles",
            ),
        ),
    ]
