# Generated by Django 2.0.3 on 2018-08-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0006_auto_20180705_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('owner', models.CharField(choices=[('project chair', 'project chair'), ('employer/ee', 'employer/ee'), ('service chair', 'service chair'), ('treasurer', 'treasurer'), ('social/brotherhood chair', 'social/brotherhood chair'), ('recruitment chair', 'recruitment chair'), ('scholarship chair', 'scholarship chair'), ('house corporation president', 'house corporation president'), ('board member', 'board member'), ('website/social media chair', 'website/social media chair'), ('national officer', 'national officer'), ('scribe', 'scribe'), ('pd chair', 'pd chair'), ('committee chair', 'committee chair'), ('pledge/new member educator', 'pledge/new member educator'), ('regent', 'regent'), ('president', 'president'), ('regional director', 'regional director'), ('other appointee', 'other appointee'), ('vice president', 'vice president'), ('fundraising chair', 'fundraising chair'), ('rush chair', 'rush chair'), ('national director', 'national director'), ('secretary', 'secretary'), ('corresponding secretary', 'corresponding secretary'), ('risk management chair', 'risk management chair'), ('vice regent', 'vice regent'), ('rube goldberg chair', 'rube goldberg chair'), ('alumni adviser', 'alumni adviser')], max_length=50)),
                ('type', models.CharField(choices=[('sub', 'Submission'), ('form', 'Forms'), ('task', 'Task'), ('bal', 'Balance')], max_length=4)),
                ('resource', models.URLField(blank=True)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chapters.Chapter')),
            ],
            options={
                'ordering': ['chapter', '-date'],
            },
        ),
        migrations.CreateModel(
            name='TaskDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_type', models.CharField(choices=[('semester', 'Semester'), ('quarter', 'Quarter'), ('all', 'All'), ('na', 'N/A')], max_length=10)),
                ('date', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tasks.Task')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='taskchapter',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='tasks.TaskDate'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdate',
            unique_together={('task', 'date', 'school_type')},
        ),
        migrations.AlterUniqueTogether(
            name='taskchapter',
            unique_together={('task', 'date', 'chapter')},
        ),
    ]
