# Generated by Django 2.0.3 on 2018-08-04 18:03
import os
import csv
from datetime import datetime
from django.db import migrations
from django.utils.text import slugify


def load_tasks(apps, schema_editor):
    task = apps.get_model("tasks", "Task")
    task_date = apps.get_model("tasks", "TaskDate")
    with open(f'{os.path.split(__file__)[0]}/initial_data.csv', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for id_obj, row in enumerate(reader):
            print(row)
            try:
                task_obj = task.objects.get(name=row["task"])
            except task.DoesNotExist:
                task_obj = task(
                    name=row["task"],
                    slug=slugify(row["task"]),
                    owner=row["owner"],
                    type=row["type"],
                    description=row["description"],
                )
                task_obj.save()
            task_date_obj = task_date(
                task=task_obj,
                school_type=row["school_type"],
                date=datetime.strptime(row['date'], '%m/%d/%Y')
            )
            task_date_obj.save()


def migrate_data_backward(apps, schema_editor):
    task = apps.get_model("tasks", "Task")
    task.objects.all().delete()
    task_date = apps.get_model("tasks", "TaskDate")
    task_date.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_tasks,
                             migrate_data_backward),
    ]
