# Generated by Django 2.0.3 on 2018-08-09 05:50
from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


submit_to_task = {
    "Gear Article": "Article",
    "Audit": "Audit",
    "Awards": "Awards",
    "Hall of Fame": "Hall of Fame",
    "Lock-in": "Lockin Goals",
    "Newsletter for Alumni": "Newsletter",
    "Outstanding Student Member": "OSM",
    "Pledge Program": "Pledge Program",
    "Annual Report Submission": "Report",
    "Risk Management Form": "RMP",
    "Scholarship": "Scholarship App",
}

task_to_form = {
    "Initiation Report": "forms:init_selection",
    "Member Updates": "forms:status_selection",
    "Pledge Forms": "http://thetatau.org/pledgeform",
    "Officer Election Report": "forms:officer"
}


def add_submission_link(apps, schema_editor):
    return
    task = apps.get_model("tasks", "Task")
    submit_type = apps.get_model("scores", "ScoreType")
    for task_obj in task.objects.all():
        submit_name = submit_to_task.get(task_obj.name, None)
        if submit_name:
            submit_name = slugify(submit_name)
            submit_type_obj = submit_type.objects.get(slug=submit_name)
            task_obj.submission_type = submit_type_obj
        form_name = task_to_form.get(task_obj.name, None)
        if form_name:
            task_obj.resource = form_name
        task_obj.save()


def delete(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20180808_2207'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tasks', '0002_initial_tasks_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskdate',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='task',
            name='submission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='scores.ScoreType'),
        ),
        migrations.AddField(
            model_name='taskchapter',
            name='submission_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskchapter',
            name='submission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(choices=[('alumni adviser', 'Alumni Adviser'), ('board member', 'Board Member'), ('fundraising chair', 'Fundraising Chair'), ('treasurer', 'Treasurer'), ('vice regent', 'Vice Regent'), ('other appointee', 'Other Appointee'), ('regent', 'Regent'), ('scribe', 'Scribe'), ('secretary', 'Secretary'), ('pledge/new member educator', 'Pledge/New Member Educator'), ('president', 'President'), ('service chair', 'Service Chair'), ('pd chair', 'Pd Chair'), ('vice president', 'Vice President'), ('rube goldberg chair', 'Rube Goldberg Chair'), ('social/brotherhood chair', 'Social/Brotherhood Chair'), ('house corporation president', 'House Corporation President'), ('website/social media chair', 'Website/Social Media Chair'), ('regional director', 'Regional Director'), ('corresponding secretary', 'Corresponding Secretary'), ('employer/ee', 'Employer/Ee'), ('rush chair', 'Rush Chair'), ('scholarship chair', 'Scholarship Chair'), ('national officer', 'National Officer'), ('project chair', 'Project Chair'), ('recruitment chair', 'Recruitment Chair'), ('risk management chair', 'Risk Management Chair'), ('committee chair', 'Committee Chair'), ('national director', 'National Director')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='resource',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(add_submission_link, delete),
    ]
