# Generated by Django 2.0.3 on 2018-08-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180808_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.CharField(choices=[('treasurer', 'Treasurer'), ('website/social media chair', 'Website/Social Media Chair'), ('secretary', 'Secretary'), ('social/brotherhood chair', 'Social/Brotherhood Chair'), ('committee chair', 'Committee Chair'), ('house corporation president', 'House Corporation President'), ('scribe', 'Scribe'), ('risk management chair', 'Risk Management Chair'), ('other appointee', 'Other Appointee'), ('rube goldberg chair', 'Rube Goldberg Chair'), ('alumni adviser', 'Alumni Adviser'), ('vice regent', 'Vice Regent'), ('pd chair', 'Pd Chair'), ('national officer', 'National Officer'), ('board member', 'Board Member'), ('employer/ee', 'Employer/Ee'), ('service chair', 'Service Chair'), ('national director', 'National Director'), ('vice president', 'Vice President'), ('fundraising chair', 'Fundraising Chair'), ('regent', 'Regent'), ('pledge/new member educator', 'Pledge/New Member Educator'), ('president', 'President'), ('corresponding secretary', 'Corresponding Secretary'), ('recruitment chair', 'Recruitment Chair'), ('scholarship chair', 'Scholarship Chair'), ('project chair', 'Project Chair'), ('regional director', 'Regional Director'), ('rush chair', 'Rush Chair')], max_length=50),
        ),
    ]
