# Generated by Django 2.0.3 on 2018-08-18 22:52

from django.db import migrations
from django.utils.text import slugify


def add_rmp(apps, schema_editor):
    task = apps.get_model("tasks", "Task")
    rmp_original = task.objects.get(name="Risk Management Form")
    rmp_original.resource = 'forms:rmp'
    rmp_original.type = 'form'
    rmp_original.save()
    for officer in ['scribe', 'vice regent',
                    'corresponding secretary', 'treasurer']:
        rmp = task.objects.filter(name="Risk Management Form").first()
        rmp.pk = None
        rmp.owner = officer
        rmp.slug = slugify(rmp.name + rmp.owner)
        rmp.save()
        for task_date in rmp_original.dates.all():
            task_date.pk = None
            task_date.task = rmp
            task_date.save()


def delete(apps, schema_editor):
    task = apps.get_model("tasks", "Task")
    task.objects.filter(name="Risk Management Form",
                        owner__in=['scribe', 'vice regent',
                                   'corresponding secretary', 'treasurer']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20180811_1001'),
    ]

    operations = [
        migrations.RunPython(add_rmp,
                             delete),
    ]
