# Generated by Django 2.0.3 on 2018-08-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0007_chapter_school_type'),
        ('tasks', '0006_auto_20180819_1942'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskchapter',
            unique_together={('task', 'date', 'chapter')},
        ),
        migrations.AlterUniqueTogether(
            name='taskdate',
            unique_together={('task', 'date', 'school_type')},
        ),
    ]
