# Generated by Django 4.2.23 on 2026-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_auto_20231231_2219"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdate",
            name="archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Archived (retired) dates are hidden from chapters and cannot be completed.",
                verbose_name="No Longer Needed",
            ),
        ),
        migrations.AddField(
            model_name="taskdate",
            name="archived_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskdate",
            name="archived_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
