# Generated by Django 2.0.3 on 2018-09-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20180901_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchapter',
            name='date',
            field=models.DateField(verbose_name='Task Completed Date'),
        ),
        migrations.AlterField(
            model_name='taskdate',
            name='date',
            field=models.DateField(verbose_name='Due Date'),
        ),
    ]
