# Generated by Django 2.0.3 on 2018-09-10 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20180908_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchapter',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 9, 21, 31, 53, 830138), verbose_name='Task Completed Date'),
        ),
    ]
