# Generated by Django 2.0.3 on 2018-09-17 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20180909_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskchapter',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 17, 9, 5, 23, 297471), verbose_name='Task Completed Date'),
        ),
    ]
