# Generated by Django 2.0.3 on 2019-01-14 02:24

from django.db import migrations
from django.utils.text import slugify


def add_audit(apps, schema_editor):
    task = apps.get_model("tasks", "Task")
    audit_original = task.objects.get(name="Audit",
                                      owner='treasurer')
    audit_original.resource = 'forms:audit'
    audit_original.type = 'form'
    audit_original.slug = slugify(audit_original.name + " " +
                                  audit_original.owner)
    audit_original.save()
    for officer in ['scribe', 'vice regent', 'regent',
                    'corresponding secretary']:
        new_audit = task.objects.get(name="Audit",
                                     owner='treasurer')
        new_audit.pk = None
        new_audit.owner = officer
        new_audit.slug = slugify(new_audit.name + " " + new_audit.owner)
        new_audit.save()
        for task_date in audit_original.dates.all():
            task_date.pk = None
            task_date.task = new_audit
            task_date.save()


def delete(apps, schema_editor):
    task = apps.get_model("tasks", "Task")
    task.objects.filter(name="Audit",
                        owner__in=['scribe', 'vice regent', 'regent',
                                   'corresponding secretary']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20181021_1048'),
    ]

    operations = [
        migrations.RunPython(add_audit,
                             delete),
    ]
