# Generated by Django 2.0.3 on 2019-02-25 00:46

from django.db import migrations, models


# Default is 90 days, this is exception to defaults
days_advance = {
    "Annual Report Submission": 30,
    "Audit": 30,
    "Dues": 30,
    "Initiation Report": 30,
    "Insurance Payment": 30,
    "Member Updates": 30,
    "Officer Election Report": 30,
    "Pledge Forms": 30,
}


def set_advance_dates(apps, schema_editor):
    task = apps.get_model("tasks", "Task")
    for task_obj in task.objects.all():
        if task_obj.name in days_advance:
            task_obj.days_advance = days_advance[task_obj.name]
            task_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20190217_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='days_advance',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.RunPython(set_advance_dates),
    ]
