# Generated by Django 4.2.23 on 2026-07-13 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("herald", "0005_auto_20180516_1755"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("esp", models.CharField(default="Mailjet", max_length=50)),
                ("message_id", models.CharField(db_index=True, max_length=255)),
                ("recipient", models.CharField(db_index=True, max_length=254)),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                (
                    "from_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "notification_class",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "last_status",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("first_opened_at", models.DateTimeField(blank=True, null=True)),
                ("last_opened_at", models.DateTimeField(blank=True, null=True)),
                ("open_count", models.PositiveIntegerField(default=0)),
                ("first_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("last_clicked_at", models.DateTimeField(blank=True, null=True)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                ("complained_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reject_reason",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "sent_notification",
                    models.ForeignKey(
                        blank=True,
                        help_text="The django-herald notification this message came from, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracked_emails",
                        to="herald.sentnotification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Resolved recipient member, when the address maps to a user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracked_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tracked email",
                "verbose_name_plural": "Tracked emails",
                "ordering": ("-sent_at",),
            },
        ),
        migrations.CreateModel(
            name="EmailTrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("esp", models.CharField(default="Mailjet", max_length=50)),
                (
                    "message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=30)),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("click_url", models.TextField(blank=True, default="")),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "reject_reason",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("mta_response", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "tracked_email",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="email_tracking.trackedemail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email tracking event",
                "verbose_name_plural": "Email tracking events",
                "ordering": ("-timestamp", "-created"),
            },
        ),
        migrations.AddIndex(
            model_name="trackedemail",
            index=models.Index(
                fields=["recipient", "-sent_at"], name="email_track_recipie_9bc00e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trackedemail",
            index=models.Index(
                fields=["message_id"], name="email_track_message_500676_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trackedemail",
            unique_together={("message_id", "recipient")},
        ),
        migrations.AddIndex(
            model_name="emailtrackingevent",
            index=models.Index(
                fields=["message_id", "event_type"],
                name="email_track_message_a0ee47_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emailtrackingevent",
            index=models.Index(
                fields=["event_type", "-created"], name="email_track_event_t_cd4c2a_idx"
            ),
        ),
    ]
