# Generated by Django 2.0.3 on 2018-06-14 21:26
import os
import csv
from django.db import migrations


def load_scores(apps, schema_editor):
    score = apps.get_model("scores", "ScoreType")
    with open(f'{os.path.split(__file__)[0]}/data_initial.csv', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for id_obj, row in enumerate(reader):
            score_obj = score(
                id=id_obj,
                name=row["name"],
                description=row["description"],
                section=row["section"],
                points=int(row["points"]),
                formula=row["formula"],
                name_short=row["name_short"],
                type=row["type"],
                base_points=float(row["base_points"]),
                attendance_multiplier=float(row["attendance_multiplier"]),
                member_add=float(row["member_add"]),
                special=row["special"],
            )
            score_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_scores),
    ]
