# Generated by Django 2.0.3 on 2018-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoretype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='scoretype',
            name='name_short',
        ),
        migrations.AddField(
            model_name='scoretype',
            name='alumni_add',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scoretype',
            name='guest_add',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scoretype',
            name='slug',
            field=models.SlugField(default='test', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoretype',
            name='stem_add',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='scoretype',
            name='term_points',
            field=models.PositiveIntegerField(default=0, help_text='Total number of points possible in term'),
        ),
    ]
