# Generated by Django 2.2.12 on 2022-01-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0002_year_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorechapter",
            name="year",
            field=models.IntegerField(
                choices=[
                    (2016, 2016),
                    (2017, 2017),
                    (2018, 2018),
                    (2019, 2019),
                    (2020, 2020),
                    (2021, 2021),
                    (2022, 2022),
                    (2023, 2023),
                    (2024, 2024),
                    (2025, 2025),
                    (2026, 2026),
                    (2027, 2027),
                    (2028, 2028),
                    (2029, 2029),
                ],
                default=2022,
            ),
        ),
    ]
