# Generated by Django 2.0.3 on 2018-06-14 21:26
import os
import csv
from django.db import migrations
from django.utils.text import slugify


def load_scores(apps, schema_editor):
    score = apps.get_model("scores", "ScoreType")
    # Sheet generated:
    # https://docs.google.com/spreadsheets/d/1vCVKh8MExPxg8eHTEGYx7k-KTu9QUypGwbtfliLm58A/edit#gid=22474166
    with open(f'{os.path.split(__file__)[0]}/data_initial.csv', newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for id_obj, row in enumerate(reader):
            score_obj = score(
                id=id_obj,
                name=row["name"],
                description=row["description"],
                section=row["section"],
                points=int(row["points"]),
                term_points=float(row["term points"]),
                formula=row["formula"],
                slug=slugify(row["name_short"]),
                type=row["type"],
                base_points=float(row["base_points"]),
                attendance_multiplier=float(row["attendance_multiplier"]),
                stem_add=float(row["stem_add"]),
                member_add=float(row["member_add"]),
                alumni_add=float(row["alumni_add"]),
                guest_add=float(row["guest_add"]),
                special=row["special"],
            )
            score_obj.save()


def delete_all_scores(apps, schema_editor):
    score = apps.get_model("scores", "ScoreType")
    score.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20180705_0933'),
    ]

    operations = [
        migrations.RunPython(load_scores, delete_all_scores),
    ]
