# Generated by Django 3.2.15 on 2022-08-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0003_auto_20220101_1355"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorechapter",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="scoretype",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
