# Generated by Django 3.2.15 on 2023-01-18 01:06

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scores", "0004_auto_20220820_1812"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scorechapter",
            name="year",
            field=models.IntegerField(
                default=core.models.current_year,
                validators=[
                    django.core.validators.MinValueValidator(2016),
                    django.core.validators.MaxValueValidator(
                        core.models.current_year_plus_10
                    ),
                ],
            ),
        ),
    ]
