# Generated by Django 2.0.3 on 2019-01-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_score_update_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorechapter',
            name='year',
            field=models.IntegerField(choices=[(2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=2019),
        ),
    ]
