# Generated by Django 4.2.23 on 2026-07-13 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("viewflow", "0008_jsonfield_and_artifact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "process_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="viewflow.process",
                    ),
                ),
                (
                    "nominee_name",
                    models.CharField(
                        blank=True,
                        help_text="Only needed when the nominee is not yet a member.",
                        max_length=255,
                        verbose_name="Nominee name",
                    ),
                ),
                (
                    "nominee_email",
                    models.EmailField(
                        blank=True,
                        help_text="Only needed when the nominee is not yet a member.",
                        max_length=254,
                        verbose_name="Nominee email",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("chapter", "Chapter"), ("regional", "Regional"), ("national", "National")],
                        default="national",
                        max_length=10,
                    ),
                ),
                (
                    "recommended_positions",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("alumni programs director", "Alumni Programs Director"),
                            ("candidate chapter director", "Candidate Chapter Director"),
                            ("council delegate", "Council Delegate"),
                            ("educational foundation board of director", "Educational Foundation Board Of Director"),
                            ("expansion director", "Expansion Director"),
                            ("grand inner guard", "Grand Inner Guard"),
                            ("grand marshal", "Grand Marshal"),
                            ("grand outer guard", "Grand Outer Guard"),
                            ("grand regent", "Grand Regent"),
                            ("grand scribe", "Grand Scribe"),
                            ("grand treasurer", "Grand Treasurer"),
                            ("grand vice regent", "Grand Vice Regent"),
                            ("national director", "National Director"),
                            ("national officer", "National Officer"),
                            ("national operations manager", "National Operations Manager"),
                            ("professional development director", "Professional Development Director"),
                            ("regional director", "Regional Director"),
                            ("service director", "Service Director"),
                        ],
                        help_text="One or more positions from the national-officer roles.",
                        max_length=1000,
                        verbose_name="Recommended position(s)",
                    ),
                ),
                ("reason", models.TextField(verbose_name="Reason for recommendation")),
                (
                    "discussed_with_nominee",
                    models.BooleanField(
                        default=False, verbose_name="I have discussed this nomination with the nominee"
                    ),
                ),
                (
                    "not_interested",
                    models.BooleanField(
                        default=False, help_text="Set when the nominee declines; blocks future recommendations."
                    ),
                ),
                ("consent_token", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    "consent_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("interested", "Interested"),
                            ("not_interested", "Not interested"),
                            ("follow_up_later", "Follow up later"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("vetting_passed", models.BooleanField(blank=True, null=True)),
                ("interview_passed", models.BooleanField(blank=True, null=True)),
                ("training_completed", models.BooleanField(default=False)),
                ("confirmed", models.BooleanField(blank=True, null=True)),
                ("appointed", models.BooleanField(default=False)),
                ("consent_notes", models.TextField(blank=True)),
                ("vetting_notes", models.TextField(blank=True)),
                ("interview_notes", models.TextField(blank=True)),
                ("training_notes", models.TextField(blank=True)),
                ("confirmation_notes", models.TextField(blank=True)),
                ("appointment_notes", models.TextField(blank=True)),
                (
                    "nominator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nominee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The member being nominated, if they already have a record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nominations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("viewflow.process",),
        ),
    ]
