# Generated by Django 4.2.23 on 2026-07-13 04:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="consent_token_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nomination",
            name="interested_level",
            field=models.CharField(
                blank=True,
                choices=[("chapter", "Chapter"), ("regional", "Regional"), ("national", "National")],
                max_length=10,
                verbose_name="Level the nominee is interested in",
            ),
        ),
        migrations.AddField(
            model_name="nomination",
            name="interested_positions",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("alumni programs director", "Alumni Programs Director"),
                    ("candidate chapter director", "Candidate Chapter Director"),
                    ("council delegate", "Council Delegate"),
                    ("educational foundation board of director", "Educational Foundation Board Of Director"),
                    ("expansion director", "Expansion Director"),
                    ("grand inner guard", "Grand Inner Guard"),
                    ("grand marshal", "Grand Marshal"),
                    ("grand outer guard", "Grand Outer Guard"),
                    ("grand regent", "Grand Regent"),
                    ("grand scribe", "Grand Scribe"),
                    ("grand treasurer", "Grand Treasurer"),
                    ("grand vice regent", "Grand Vice Regent"),
                    ("national director", "National Director"),
                    ("national officer", "National Officer"),
                    ("national operations manager", "National Operations Manager"),
                    ("professional development director", "Professional Development Director"),
                    ("regional director", "Regional Director"),
                    ("service director", "Service Director"),
                ],
                max_length=1000,
                verbose_name="Positions the nominee is interested in",
            ),
        ),
    ]
