# Generated by Django 4.2.23 on 2026-07-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0002_nomination_consent_token_expires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nomination",
            name="last_contacted",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
