# Generated by Django 4.2.23 on 2026-07-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0003_nomination_last_activity_nomination_last_contacted"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="reference_check",
            field=models.BooleanField(default=False, verbose_name="Reference / background check completed"),
        ),
    ]
