# Generated by Django 4.2.23 on 2026-07-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0004_nomination_reference_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="interview_conducted",
            field=models.BooleanField(default=False, verbose_name="Interview conducted"),
        ),
        migrations.AddField(
            model_name="nomination",
            name="interview_date",
            field=models.DateField(blank=True, null=True, verbose_name="Interview date"),
        ),
    ]
