# Generated by Django 4.2.23 on 2026-07-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0005_nomination_interview_conducted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="training_cmt_complete",
            field=models.BooleanField(default=False, verbose_name="CMT LMS Volunteer Training complete"),
        ),
        migrations.AddField(
            model_name="nomination",
            name="training_vector_complete",
            field=models.BooleanField(default=False, verbose_name="Vector CommunityEdu H&S Training complete"),
        ),
    ]
