# Generated by Django 4.2.23 on 2026-07-13 04:45

from django.db import migrations, models
import thetatauCMT.nominations.models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0006_nomination_training_cmt_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="added_to_natoff_lists",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nomination",
            name="appointment_letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=thetatauCMT.nominations.models.get_appointment_letter_path,
                verbose_name="Appointment letter",
            ),
        ),
        migrations.AddField(
            model_name="nomination",
            name="appointment_letter_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nomination",
            name="chapters_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="nomination",
            name="ppm_ordered",
            field=models.BooleanField(default=False, verbose_name="PPM ordered"),
        ),
    ]
