# Generated by Django 4.2.23 on 2026-07-13 04:52

from django.db import migrations, models
import thetatauCMT.nominations.models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0007_nomination_added_to_natoff_lists_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="denial_letter",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=thetatauCMT.nominations.models.get_denial_letter_path,
                verbose_name="Denial letter",
            ),
        ),
        migrations.AddField(
            model_name="nomination",
            name="denial_letter_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="nomination",
            name="denial_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="nomination",
            name="rejection_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
