# Generated by Django 4.2.23 on 2026-07-13 16:19

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0008_nomination_denial_letter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomination",
            name="interested_level",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[("chapter", "Chapter"), ("regional", "Regional"), ("national", "National")],
                max_length=30,
                verbose_name="Level(s) the nominee is interested in",
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="level",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("chapter", "Chapter"), ("regional", "Regional"), ("national", "National")],
                default="national",
                help_text="One or more levels the member is being recommended for.",
                max_length=30,
                verbose_name="Level(s)",
            ),
        ),
        migrations.AlterField(
            model_name="nomination",
            name="reason",
            field=models.TextField(
                help_text="This will be shared with the nominee.", verbose_name="Reason for recommendation"
            ),
        ),
        migrations.CreateModel(
            name="NominationContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(max_length=50)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("recipient", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="nominations.nomination",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
