# Generated by Django 4.2.23 on 2026-08-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0009_alter_nomination_interested_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomination",
            name="training_vector_complete",
            field=models.BooleanField(default=False, verbose_name="Vector CommunityEDU H&S Training complete"),
        ),
    ]
