# Generated by Django 2.0.3 on 2018-06-14 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('guests', models.PositiveIntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('stem', models.BooleanField(default=False, help_text='Does the event relate to Science Technology Engineering or Math (STEM)?')),
                ('host', models.BooleanField(default=False, help_text='Did this event host another chapter?')),
                ('miles', models.PositiveIntegerField(default=0, help_text='Miles traveled to an event hosted by another chapter.')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chapters.Chapter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
