# Generated by Django 2.2.12 on 2020-05-17 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("scores", "0001_initial"),
        ("chapters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, verbose_name="Event Name")),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Event Date"
                    ),
                ),
                ("slug", models.SlugField()),
                ("score", models.FloatField(default=0)),
                ("description", models.CharField(max_length=200)),
                ("members", models.PositiveIntegerField(default=0)),
                ("alumni", models.PositiveIntegerField(default=0)),
                ("pledges", models.PositiveIntegerField(default=0)),
                ("guests", models.PositiveIntegerField(default=0)),
                ("duration", models.PositiveIntegerField(default=0)),
                (
                    "stem",
                    models.BooleanField(
                        default=False,
                        help_text="Does the event relate to Science Technology Engineering or Math (STEM)?",
                    ),
                ),
                (
                    "host",
                    models.BooleanField(
                        default=False, help_text="Did this event host another chapter?"
                    ),
                ),
                (
                    "miles",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Miles traveled to an event hosted by another chapter.",
                    ),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="chapters.Chapter",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="scores.ScoreType",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "date", "chapter")},
            },
        ),
    ]
