# Generated by Django 2.0.3 on 2018-07-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapters', '0006_auto_20180705_1132'),
        ('events', '0002_auto_20180614_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alumni',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='pledges',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('name', 'date', 'chapter')},
        ),
    ]
