# Generated by Django 4.2.23 on 2026-07-10 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0006_alter_region_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0007_auto_20231231_2219"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="approval_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="approved",
                help_text="Approval state for public events. Non-public events do not require approval.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_national",
            field=models.BooleanField(
                default=False, help_text="National event (organization-wide). Only National Officers may create these."
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Public event. Public events created by chapter officers require National Officer approval before they become visible to other chapters.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="parent_event",
            field=models.ForeignKey(
                blank=True,
                help_text="If this is a sub-event, the parent event it belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_events",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="region",
            field=models.ForeignKey(
                blank=True,
                help_text="Region context for the event. Sub-events inherit this from their parent unless overridden.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="regions.region",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Optional reason recorded when a public event is rejected.", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Reviewed at"),
        ),
        migrations.AddField(
            model_name="event",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="National Officer who approved or rejected this public event.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_reviewed",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Reviewed by",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="pledges",
            field=models.PositiveIntegerField(default=0, verbose_name="PNMs"),
        ),
    ]
