# Generated by Django 4.2.23 on 2026-07-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0015_add_address_socials_to_chapter"),
        ("events", "0008_event_approval_status_event_is_national_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="chapter",
            field=models.ForeignKey(
                blank=True,
                help_text="The chapter that owns this event. National events are org-wide and not tied to a chapter.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="chapters.chapter",
            ),
        ),
    ]
