# Generated by Django 4.2.23 on 2026-07-11 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0015_add_address_socials_to_chapter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regions", "0006_alter_region_id"),
        ("events", "0009_alter_event_chapter"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarFeedSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("token", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(default="My Theta Tau Calendar", max_length=100)),
                (
                    "include_national",
                    models.BooleanField(default=True, help_text="Include national (organization-wide) events."),
                ),
                (
                    "include_todos",
                    models.BooleanField(
                        default=False, help_text="Include your chapter's outstanding to-dos (as calendar tasks)."
                    ),
                ),
                (
                    "chapters",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Public events from these chapters.",
                        related_name="calendar_feeds",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "regions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Public events from every chapter in these regions.",
                        related_name="calendar_feeds",
                        to="regions.region",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_feeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
