# Generated by Django 4.2.23 on 2026-07-11 04:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_calendarfeedsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarfeedsubscription",
            name="task_owner_roles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("corresponding secretary", "Corresponding Secretary"),
                        ("regent", "Regent"),
                        ("scribe", "Scribe"),
                        ("treasurer", "Treasurer"),
                        ("vice regent", "Vice Regent"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Limit to-dos to these officer roles' tasks (empty = every role's tasks).",
                size=None,
            ),
        ),
    ]
