# Generated by Django 4.2.23 on 2026-07-15 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0011_calendarfeedsubscription_task_owner_roles"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"base_manager_name": "all_objects", "default_manager_name": "objects"},
        ),
        migrations.AlterModelManagers(
            name="event",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="deleted",
            field=models.BooleanField(
                db_index=True, default=False, help_text="Soft-deleted events are hidden and excluded from scoring."
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Deleted at"),
        ),
        migrations.AddField(
            model_name="event",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted by",
            ),
        ),
    ]
