# Generated by Django 4.2.23 on 2026-08-11 15:38

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_event_options_alter_event_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="external_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional link to a registration page, flyer, or other event info.",
                max_length=500,
                verbose_name="More Info Link",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(
                blank=True,
                help_text="When the event starts. Leave blank for an all-day event.",
                null=True,
                verbose_name="Start Time",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="time_zone",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Time zone the start time is given in. Leave blank to use the site default.",
                max_length=64,
                verbose_name="Time Zone",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="What is the event about? For an upcoming event, include anything a member needs to know to show up: where to meet, what to bring, who to contact.",
                verbose_name="Description",
            ),
        ),
    ]
