# Generated by Django 2.0.3 on 2018-06-14 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('website', models.URLField()),
                ('facebook', models.URLField()),
                ('directors', models.ManyToManyField(related_name='region', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
