# Generated by Django 2.2.12 on 2020-05-17 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="directors",
            field=models.ManyToManyField(
                related_name="region", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
