# Generated by Django 2.2.12 on 2020-12-30 22:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0002_region_directors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="directors",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="region",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
