# Generated by Django 2.2.12 on 2022-04-10 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0003_auto_20201230_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="directors",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="regional_director",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
