# Generated by Django 2.2.12 on 2022-07-04 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("regions", "0004_auto_20220410_1131"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="directors",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="regional_director",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
