# Generated by Django 3.2.15 on 2025-02-24 00:37

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_userforeignkey.models.fields
import jobs.models
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address", "0003_auto_20200830_1851"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Major",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="JobSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "search_title",
                    models.CharField(max_length=255, verbose_name="Search Name"),
                ),
                (
                    "search_description",
                    models.CharField(
                        help_text="Provide a short description to help you remember this search",
                        max_length=255,
                        verbose_name="Search Description",
                    ),
                ),
                (
                    "contact",
                    models.BooleanField(
                        blank=True,
                        choices=[(None, "Any"), (True, "Yes"), (False, "No")],
                        default=None,
                        help_text="Is there a contact for the job?",
                        null=True,
                        verbose_name="Contact",
                    ),
                ),
                (
                    "contact_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        help_text="Contains search, leave blank to not search on this field",
                        max_length=255,
                        null=True,
                        verbose_name="Company Name Contains",
                    ),
                ),
                (
                    "company_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Contains search, leave blank to not search on this field",
                        max_length=255,
                        null=True,
                        verbose_name="Description Contains",
                    ),
                ),
                (
                    "description_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "education_qualification",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            (None, "Any"),
                            ("highschool", "High School"),
                            ("bachelors", "Bachelors"),
                            ("masters", "Masters"),
                            ("phd", "PhD"),
                        ],
                        default=None,
                        help_text="What education is needed for this job?",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "education_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "experience",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            (None, "Any"),
                            ("in_school", "In School"),
                            ("new_grad", "New Grad"),
                            ("less_than_one", "1 < years"),
                            ("less_than_five", "1 < years < 5"),
                            ("less_than_ten", "5 < years < 10"),
                            ("less_than_fifteen", "10 < years < 15"),
                            ("less_than_twenty", "15 < years < 20"),
                            ("twenty_plus", "20 < years"),
                        ],
                        default=None,
                        help_text="What experience is needed for this job?",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "experience_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "job_type",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            (None, "Any"),
                            ("intern", "Internship"),
                            ("coop", "Co-op"),
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contractor", "Contractor"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "job_type_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "location_type",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            (None, "Any"),
                            ("on_site", "On Site"),
                            ("hybrid", "Hybrid"),
                            ("flexible", "Flexible"),
                            ("dedicated_office", "Dedicated Office"),
                            ("remote", "Remote"),
                        ],
                        default=None,
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "location_type_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "sponsored",
                    models.BooleanField(
                        blank=True,
                        choices=[(None, "Any"), (True, "Yes"), (False, "No")],
                        default=None,
                        help_text="Is the job posting sponsored by a company?",
                        null=True,
                        verbose_name="Sponsored",
                    ),
                ),
                (
                    "sponsored_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Contains search, leave blank to not search on this field",
                        max_length=255,
                        null=True,
                        verbose_name="Title Contains",
                    ),
                ),
                (
                    "title_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "keywords_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "majors_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "location_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "country_filter",
                    models.CharField(
                        choices=[
                            ("include", "Must match"),
                            ("optional", "Optionally match"),
                            ("exclude", "Does not match"),
                        ],
                        default="include",
                        max_length=20,
                    ),
                ),
                (
                    "notification",
                    models.CharField(
                        choices=[
                            ("none", "Get no notification emails on matching jobs."),
                            (
                                "immediate",
                                "Get notified immediately of a new matching job.",
                            ),
                            (
                                "daily",
                                "Get a daily email digests of new matching jobs.",
                            ),
                            (
                                "weekly",
                                "Get a weekly email digests of new matching jobs.",
                            ),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Do you want to be notified of matching new jobs?",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_searches",
                        to="address.country",
                    ),
                ),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_searches_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that created this object",
                    ),
                ),
                (
                    "keywords",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        help_text="Keywords to help job searchers find this job",
                        related_name="job_searches",
                        to="jobs.Keyword",
                    ),
                ),
                (
                    "location",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        help_text="What is the location of jobs",
                        related_name="job_searches",
                        to="address.Locality",
                    ),
                ),
                (
                    "majors",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        help_text="Majors to search for",
                        related_name="job_searches",
                        to="jobs.Major",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Search",
                "ordering": ["-modified"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.BooleanField(
                        choices=[
                            (
                                True,
                                "Yes, please reach out. Your name and email will show on the job listing.",
                            ),
                            (
                                False,
                                "No, contact the job posting only. Your name and email will NOT show on the job listing",
                            ),
                        ],
                        default=True,
                        help_text="Are you available to answer questions about the job?",
                        verbose_name="Contact",
                    ),
                ),
                (
                    "other_contact",
                    models.CharField(
                        blank=True,
                        help_text="Is there another contact email or phone number for this job listing?",
                        max_length=1000,
                        null=True,
                        verbose_name="Other Contact",
                    ),
                ),
                (
                    "company",
                    models.CharField(max_length=255, verbose_name="Company Name"),
                ),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text="No need to copy the entire job post, please share most relevant details or anything else to help job searchers"
                    ),
                ),
                (
                    "education_qualification",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("highschool", "High School"),
                            ("bachelors", "Bachelors"),
                            ("masters", "Masters"),
                            ("phd", "PhD"),
                        ],
                        help_text="What education is needed for this job?",
                        max_length=255,
                    ),
                ),
                (
                    "experience",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("in_school", "In School"),
                            ("new_grad", "New Grad"),
                            ("less_than_one", "1 < years"),
                            ("less_than_five", "1 < years < 5"),
                            ("less_than_ten", "5 < years < 10"),
                            ("less_than_fifteen", "10 < years < 15"),
                            ("less_than_twenty", "15 < years < 20"),
                            ("twenty_plus", "20 < years"),
                        ],
                        help_text="What experience is needed for this job?",
                        max_length=255,
                    ),
                ),
                (
                    "job_type",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("intern", "Internship"),
                            ("coop", "Co-op"),
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contractor", "Contractor"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "location_type",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("on_site", "On Site"),
                            ("hybrid", "Hybrid"),
                            ("flexible", "Flexible"),
                            ("dedicated_office", "Dedicated Office"),
                            ("remote", "Remote"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "publish_end",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="When the job post should NO LONGER be available for job searchers.",
                    ),
                ),
                (
                    "publish_start",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="When the job post should be available for job searchers.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "sponsored",
                    models.BooleanField(
                        choices=[
                            (True, "This job posting was sponsored by a company"),
                            (False, "This job posting was created/shared by a member"),
                        ],
                        default=False,
                        help_text="Is the job posting sponsored by a company?",
                        verbose_name="Sponsored",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "url",
                    models.URLField(
                        help_text="What is the link for more information about the job?"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ],
                        default=10,
                        help_text="The order you want Jobs to appear in, 1 will be on top. Sorted by priority and then reverse published start date",
                        verbose_name="Priority order, 1 highest",
                    ),
                ),
                (
                    "majors_specific",
                    models.BooleanField(
                        choices=[
                            (True, "Yes, listed below"),
                            (False, "No, job posting is open to any and all majors"),
                        ],
                        default=False,
                        help_text="Are there specific majors this job listing is targeted for?",
                        verbose_name="Specific Majors",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=jobs.models.get_job_attachment_upload_path,
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="address.country",
                    ),
                ),
                (
                    "created_by",
                    django_userforeignkey.models.fields.UserForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="The user that created this object",
                    ),
                ),
                (
                    "keywords",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        help_text="Keywords to help job searchers find this job",
                        related_name="jobs",
                        to="jobs.Keyword",
                    ),
                ),
                (
                    "location",
                    models.ManyToManyField(
                        help_text="What is the location of the main office even if the job is remote.",
                        related_name="jobs",
                        to="address.Locality",
                    ),
                ),
                (
                    "majors",
                    models.ManyToManyField(
                        blank=True,
                        default=None,
                        help_text="If the job posting is for specific majors only, what are those majors?",
                        related_name="jobs",
                        to="jobs.Major",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "ordering": ["priority", "-publish_start"],
            },
        ),
    ]
