# Generated by Django 4.2.23 on 2026-07-04 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deleted",
            field=models.BooleanField(
                default=False,
                help_text="Soft-delete flag. Hidden from all listings and detail views when True.",
                verbose_name="Deleted",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
        ),
        migrations.AddField(
            model_name="job",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs_deleted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
