# Generated by Django 4.2.23 on 2026-07-04 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0002_job_deleted_job_deleted_at_job_deleted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="approved",
            field=models.BooleanField(
                default=False,
                help_text="Set to True by a National Officer to mark a posting as reviewed and legitimate.",
                verbose_name="Approved",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Approved At"),
        ),
        migrations.AddField(
            model_name="job",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="reported",
            field=models.BooleanField(
                default=False,
                help_text="Set to True when a member has reported this posting for review.",
                verbose_name="Reported",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="reported_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Reported At"),
        ),
        migrations.AddField(
            model_name="job",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs_reported",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="reported_reason",
            field=models.TextField(blank=True, default="", verbose_name="Report Reason"),
        ),
    ]
