# Generated by Django 4.2.23 on 2026-07-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_approved_job_approved_at_job_approved_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="approved_reason",
            field=models.TextField(blank=True, default="", verbose_name="Approve Reason"),
        ),
        migrations.AddField(
            model_name="job",
            name="deleted_reason",
            field=models.TextField(blank=True, default="", verbose_name="Delete Reason"),
        ),
    ]
