# Generated by Django 4.2.23 on 2026-07-23 22:32

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0005_jobpostingban"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_by",
            field=django_userforeignkey.models.fields.UserForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs_created",
                to=settings.AUTH_USER_MODEL,
                verbose_name="The user that created this object",
            ),
        ),
    ]
